ui/web-v2/apps/admin/src/components/AccountAddForm/index.tsx
ui/web-v2/apps/admin/tsconfig.json

I adapted only one file since there are many target files.

refactor: web-v2-app-admin support absolute import

---

.github/workflows/pr-python.yaml

Action results: https://github.com/bucketeer-io/bucketeer/actions/runs/3239248067/jobs/5308401842

ci: add action workflow to validate pull requests for python development

---

pkg/metricsevent/storage/event.go

This PR doesn't change any behavior.

refactor: add param names in Storage interface

---

Makefile
pkg/ldflags/ldflags.go

- Using ldflags to set version information for go applications.

chore: set version using ldflags

---

pkg/feature/api/feature.go

The user should be able to update even if the feature is already archived.

fix: failed to find feature while trying to update an archived feature

---

.github/workflows/push-image.yaml
tools/build/show-dockerfile.sh
tools/build/show-image-name.sh
ui/web-v2/Dockerfile

- I added workflow to build and push images
- Set IMAGE_TAG
- build and push
- go
- python
- web
- dispatch to another repo
- notify slack
**note:** Before merging this PR, there are two requirements the followings.

ci: add action workflow to build and push images

---

.github/workflows/pr-go.yaml
Makefile
proto/Makefile

- added validation to check proto-descriptor to actions workflow.

ci: add validation to check proto-descriptor

---

pkg/eventpersister/cmd/server/server.go
pkg/eventpersister/persister/persister.go
pkg/eventpersister/persister/persister_test.go

Related to https://github.com/bucketeer-io/bucketeer/pull/80

chore: add experiment client in the event-persister service

---

.github/workflows/push-image.yaml

- I added github actions steps to push docker images to Google Artifact Registry in addition to GHCR.

ci: add steps to push docker images to GAR

---

.github/workflows/publish_chart.yaml

- I added steps to push the helm chart to Google Artifact Registry

ci: add steps to push helm chart to GAR

---

.github/workflows/pr-go.yaml
.github/workflows/push-image.yaml

Fix reference:
https://github.com/actions/runner-images/issues/602#issuecomment-603035769

ci: fix api rate limit exceeded for arduino/setup-protoc

---

.github/workflows/push-image.yaml

Because we have many images to push to the registry, I changed it to push all images in parallel to speed up this process.

ci: run the push images in parallel to speed up the process

---

ui/web-v2/apps/admin/src/assets/lang/en.json
ui/web-v2/apps/admin/src/assets/lang/ja.json
ui/web-v2/apps/admin/src/components/FeatureAddForm/index.tsx
ui/web-v2/apps/admin/src/components/FeatureVariationsForm/index.tsx
ui/web-v2/apps/admin/src/components/VariationInput/index.tsx
ui/web-v2/apps/admin/src/lang/messages.ts
ui/web-v2/apps/admin/src/pages/feature/index.tsx

Fix https://github.com/bucketeer-io/bucketeer/issues/142 https://github.com/bucketeer-io/bucketeer/issues/138

fix(ui): show popup variation rule message while hovering on variation delete button

---

pkg/gateway/api/api.go
pkg/gateway/api/api_test.go
pkg/gateway/api/register_event_type.go
test/e2e/autoops/auto_ops_test.go
test/e2e/eventcounter/eventcounter_test.go
test/e2e/feature/feature_last_used_info_test.go
test/e2e/gateway/api_test.go
test/e2e/util/rest.go

I'm fixing the e2e test by creating a file with the register event type to avoid different implementations in the e2e tests and the gateway package.

test: invalid message type in the e2e test

---

ui/web-v2/apps/admin/src/components/TimeseriesLineChart/index.tsx

Fix https://github.com/bucketeer-io/bucketeer/issues/140

fix(ui): experiement crash

---

manifests/bucketeer/charts/calculator/templates/deployment.yaml
manifests/bucketeer/charts/calculator/values.yaml
manifests/bucketeer/values.yaml
python/src/cmd/calculator/main.py

- Added job schedule options to the calculator to tweak.

chore: add job schedule options to calculator flags

---

manifests/bucketeer/charts/event-persister-evaluation-events-dwh/.helmignore
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/Chart.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/templates/_helpers.tpl
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/templates/hpa.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/templates/service-account.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/templates/service-cert-secret.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/templates/service-token-secret.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/templates/service.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/values.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/.helmignore
manifests/bucketeer/charts/event-persister-goal-events-dwh/Chart.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/templates/_helpers.tpl
manifests/bucketeer/charts/event-persister-goal-events-dwh/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/templates/hpa.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/templates/service-account.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/templates/service-cert-secret.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/templates/service-token-secret.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/templates/service.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/values.yaml
manifests/bucketeer/values.yaml
tools/build/show-image-name.sh

This is  https://github.com/bucketeer-io/bucketeer/pull/154 with `/cmd` directory removed.

chore: add manifest files for event persister dwh

---

ui/web-v2/apps/admin/src/pages/index.tsx

As part of renewing the data pipeline, I'm disabling this feature temporarily.

chore(ui): disable analysis menu

---

ui/web-v2/apps/admin/src/components/FeatureTargetingForm/index.tsx
ui/web-v2/apps/admin/src/pages/feature/targeting.tsx

Fix https://github.com/bucketeer-io/bucketeer/issues/139

fix(ui): fix validation in targeting rule

---

ui/web-v2/apps/admin/src/components/FeatureAutoOpsRulesForm/index.tsx
ui/web-v2/apps/admin/src/pages/feature/autoops.tsx

Fix https://github.com/bucketeer-io/bucketeer/issues/141

fix(ui): auto ops validation

---

pkg/eventcounter/api/api.go
pkg/eventcounter/api/api_test.go
pkg/eventcounter/storage/v2/event.go
pkg/eventcounter/storage/v2/mock/event.go
pkg/eventcounter/storage/v2/sql/goal_count.sql

- Fixed SQL 
- Added goalID to the SQL where clause to filter

fix: eventcounter doesn't return goal counts

---

go.mod
test/e2e/eventcounter/eventcounter_test.go

- Added eventcounter's e2e test for new APIs using BigQuery as upstream.
- Removed eventcounter's e2e test for APIs using Druid as upstream.

test: update eventcounter e2e

---

ui/web-v2/apps/admin/src/assets/lang/en.json
ui/web-v2/apps/admin/src/assets/lang/ja.json
ui/web-v2/apps/admin/src/components/CreatableSelect/index.tsx
ui/web-v2/apps/admin/src/components/FeatureAddForm/index.tsx
ui/web-v2/apps/admin/src/components/FeatureList/index.tsx
ui/web-v2/apps/admin/src/components/FeatureSettingsForm/index.tsx
ui/web-v2/apps/admin/src/components/FilterPopover/index.tsx
ui/web-v2/apps/admin/src/components/PushAddForm/index.tsx
ui/web-v2/apps/admin/src/components/PushUpdateForm/index.tsx
ui/web-v2/apps/admin/src/grpc/features.ts
ui/web-v2/apps/admin/src/lang/messages.ts
ui/web-v2/apps/admin/src/modules/features.ts
ui/web-v2/apps/admin/src/modules/index.ts
ui/web-v2/apps/admin/src/modules/tags.ts
ui/web-v2/apps/admin/src/pages/feature/index.tsx
ui/web-v2/apps/admin/src/pages/push/index.tsx
ui/web-v2/apps/admin/src/types/feature.ts

Solves https://github.com/bucketeer-io/bucketeer/issues/178

feat(ui): tags

---

manifests/bucketeer/charts/auto-ops/values.yaml
manifests/bucketeer/charts/notification/values.yaml
manifests/bucketeer/charts/push/values.yaml

- I removed default settings for hpa as well as other modules.

chore: remove default values from hpa

---

test/e2e/eventcounter/eventcounter_test.go

```shell
=== PAUSE TestGrpcExperimentEvaluationEventCount
=== RUN   TestExperimentEvaluationEventCount
=== PAUSE TestExperimentEvaluationEventCount
=== RUN   TestGetEvaluationTimeseriesCount
=== PAUSE TestGetEvaluationTimeseriesCount
=== CONT  TestGrpcExperimentGoalCount
=== CONT  TestMultiGoalsEventCounterRealtime
=== CONT  TestGrpcExperimentResult
=== CONT  TestExperimentEvaluationEventCount
=== CONT  TestGetEvaluationTimeseriesCount
=== CONT  TestExperimentResultWithoutTag
=== CONT  TestExperimentGoalCount
=== CONT  TestGrpcExperimentEvaluationEventCount
=== CONT  TestHTTPTrack
=== CONT  TestGrpcMultiGoalsEventCounterRealtime
--- PASS: TestGetEvaluationTimeseriesCount (11.17s)
=== CONT  TestExperimentResult
--- PASS: TestGrpcExperimentEvaluationEventCount (11.54s)
--- PASS: …
```

test: e2e tests for GetEvaluationTimeseriesCount

---

pkg/eventpersisterdwh/persister/goal_event.go
pkg/eventpersisterdwh/persister/persister_test.go

Currently, if the user runs two or more experiments using the same goal ID, it will only link the goal event to the first item in the experiment list. 
So I'm adding support to create one or more goal events according to the number of experiments that contain the same goal ID.

chore: add support for multiple experiments using the same goal id

---

.github/workflows/cla.yaml

https://github.com/contributor-assistant/github-action#5-users-and-bots-in-allowlist

chore: add renovate to cla allowlist

---

renovate.json

- It seems that auto-merge works on UTC.

ci: change renovate auto-merge schedule

---

test/e2e/gateway/api_grpc_test.go

- replaced `web` SDK with `JAVASCRIPT` SDK.
- changed to create multiple types of APIID and SourceD metrics events.

test: improve e2e for registering metrics events

---

.github/workflows/pr-python.yaml

Reverts bucketeer-io/bucketeer#241

revert: add build step to workflow for validating pull request for python

---

ui/web-v2/apps/admin/src/components/CreatableSelect/index.tsx

Solve https://github.com/bucketeer-io/bucketeer/issues/257

chore(ui): add the option to delete values individually in the select menu

---

manifests/bucketeer/charts/user-persister/templates/deployment.yaml
manifests/bucketeer/charts/user-persister/templates/envoy-configmap.yaml
manifests/bucketeer/charts/user-persister/values.yaml
pkg/user/cmd/persister/persister.go
pkg/user/persister/persister.go
pkg/user/persister/persister_test.go

- This PR removes the feature persisting user data to MySQL
- We don't use the data now, and this process is using too many MySQL resources.
- We decided to remove the service until we decide again what to do with the user metadata.
- This PR removes the dependency to feature service from user-persister.
- This dependency was already not in use.

chore: remove feature persisting user data

---

pkg/feature/api/segment.go

The app enters an infinite loop state when the environment has more than 500 feature flags (listRequestSize).
I could fix it by replacing the `mysql.QueryNoLimit` with the `listRequestSize` const, but to avoid this situation, I refactored it to get all features in one query. If we have any performance issues in the future, we can think of something else.

fix: out of memory while trying to delete a segment

---

pkg/feature/api/feature.go
pkg/feature/api/feature_test.go

- This PR adds a function to refresh the feature flags cache in the Redis.

chore:  add function to refresh features cache

---

pkg/gateway/api/api_grpc.go
pkg/gateway/api/metrics.go

- This PR adds a Prometheus metrics counter for evaluation type.

chore: add metrics for evaluation

---

pkg/eventcounter/api/api.go
pkg/eventcounter/api/api_test.go

This PR fixes the following things:
* Truncate hour in the current time when the unit is 24 hours
* PF count all keys when the unit is 24 hours. PF Merge keys when the unit is not 24 hours.

fix: wrong user counts in 24 hours

---

.github/dependabot.yaml

chore: update the directory for npm in dependabot

---

cmd/backend/backend.go
manifests/bucketeer/charts/backend/.helmignore
manifests/bucketeer/charts/backend/Chart.yaml
manifests/bucketeer/charts/backend/templates/NOTES.txt
manifests/bucketeer/charts/backend/templates/_helpers.tpl
manifests/bucketeer/charts/backend/templates/deployment.yaml
manifests/bucketeer/charts/backend/templates/envoy-configmap.yaml
manifests/bucketeer/charts/backend/templates/hpa.yaml
manifests/bucketeer/charts/backend/templates/oauth-key-secret.yaml
manifests/bucketeer/charts/backend/templates/pdb.yaml
manifests/bucketeer/charts/backend/templates/service-account.yaml
manifests/bucketeer/charts/backend/templates/service-cert-secret.yaml
manifests/bucketeer/charts/backend/templates/service-token-secret.yaml
manifests/bucketeer/charts/backend/templates/service.yaml
manifests/bucketeer/charts/backend/values.yaml
pkg/backend/cmd/server/server.go

Issue: https://github.com/bucketeer-io/bucketeer/issues/405
- This PR adds a new service named `backend,` which contains the functions of `auth` and `account.`
- The `backend` service is supposed to implement other functions such as the `environment,` `feature,` and so on. 
- Even if we merge this PR, no requests will be sent to the `backend` service. I will change it with the next PR.

chore: add backend service

---

.github/workflows/pr-go.yaml
Makefile
proto/Makefile

This PR cherry-picks https://github.com/bucketeer-io/bucketeer/pull/408.
As https://github.com/bucketeer-io/bucketeer/pull/398#issuecomment-1579930517, we need to validate generated files from proto-go

ci: add proto-go-check command

---

manifests/bucketeer/charts/backend/templates/deployment.yaml
manifests/bucketeer/charts/backend/templates/envoy-configmap.yaml
manifests/bucketeer/charts/backend/values.yaml
pkg/backend/cmd/server/server.go

- This PR integrates the event-counter, experiment, and feature service into the backend module.
- Even if this PR is merged, requests will be sent to the event-counter, experiment, and feature services from the web-gateway.

chore: add event-counter, experiment, feature service into the backend module

---

manifests/bucketeer/charts/calculator/templates/deployment.yaml
manifests/bucketeer/charts/calculator/values.yaml

I forgot to implement the envoy admin ready API in the calculator service.

fix: calculator envoy health check

---

pkg/gateway/api/api.go
pkg/gateway/api/api_grpc.go

- This PR modifies the api-gateway behavior when it fetches features from Redis.
- After merging this PR, the api-gateway accesses Redis without single flight.
- When the features cache doesn't exist in Redis, the api-gateway fetches features from the feature server in the backend service with single flight.

perf: modify api-gateway to fetch features cache without single flight

---

pkg/gateway/api/api.go
pkg/gateway/api/api_grpc.go

Reverts bucketeer-io/bucketeer#508

revert: modify api-gateway to fetch features cache without single flight

---

pkg/gateway/api/api_grpc.go

- This PR adds tracing settings with OpenCensus.
- Although OpenCensus' Go library was archived on 1st August 2023, we continue to use it for now.
- We plan to replace it with OpenTelemetry after [Pub/Sub library supports Otel](https://github.com/googleapis/google-cloud-go/issues/4665).

chore: add tracing settings

---

pkg/account/api/account_test.go
pkg/account/api/admin_account_test.go
pkg/account/api/api_key_test.go
pkg/auditlog/api/api_test.go
pkg/autoops/api/api_test.go
pkg/autoops/api/webhook_test.go
pkg/environment/api/environment_test.go
pkg/environment/api/environment_v2_test.go
pkg/environment/api/project_test.go
pkg/eventcounter/api/api_test.go
pkg/experiment/api/api_test.go
pkg/experiment/api/experiment_test.go
pkg/experiment/api/goal_test.go
pkg/feature/api/feature_test.go
pkg/feature/api/segment_test.go
pkg/feature/api/segment_user_test.go
pkg/locale/locale.go
pkg/locale/localizedata/en.yaml
pkg/locale/localizedata/ja.yaml
pkg/locale/localizer_test.go
pkg/notification/api/admin_subscription_test.go
pkg/notification/api/subscription_test.go
pkg/push/api/api_test.go

- Translated the status and error messages to English
- Fixed the context in the unit test not including the metadata

chore: translate the localize file from Japanese to English

---

.github/workflows/code-butler.yaml

Code-Butler is a tool that utilizes AI to conduct code reviews.
I believe that implementing this tool will be helpful for our code review process.
Swift code reviews are also crucial for development productivity.
https://github.com/ca-dp/code-butler
OPENAI_API_KEY must be set in Repository secrets of Actions.

build: add code-butler

---

manifests/bucketeer/charts/batch/templates/deployment.yaml
manifests/bucketeer/charts/batch/values.yaml
pkg/batch/cmd/server/server.go

- This PR adds the mysql connection settings for the admin user.
- Only the admin user can execute ddl command.

fix: batch server cannot execute ddl to mysql

---

manifests/bucketeer/charts/batch/templates/deployment.yaml
manifests/bucketeer/charts/batch/values.yaml
pkg/batch/cmd/server/server.go

Reverts bucketeer-io/bucketeer#632

revert: fix batch server cannot execute ddl to mysql

---

Makefile

Fix https://github.com/bucketeer-io/bucketeer/issues/652
I simply add a new make command rather than automatically run docker image.
I will add the instruction about it to https://docs.bucketeer.io/contribution-guide/contributing after this PR is merged.
WDYT?

chore: add make run-httpstan

---

pkg/account/api/account.go
pkg/account/api/api.go
pkg/account/api/api_key.go
pkg/auditlog/api/api.go
pkg/auditlog/api/api_test.go
pkg/autoops/api/api.go
pkg/autoops/api/api_test.go
pkg/autoops/api/progressive_rollout.go
pkg/autoops/api/progressive_rollout_test.go
pkg/autoops/api/webhook.go
pkg/eventcounter/api/api.go
pkg/eventcounter/api/api_test.go
pkg/experiment/api/api.go
pkg/experiment/api/api_test.go
pkg/experiment/api/experiment.go
pkg/experiment/api/goal.go
pkg/feature/api/api.go
pkg/feature/api/api_test.go
pkg/feature/api/feature.go
pkg/feature/api/flag_trigger.go
pkg/feature/api/segment.go
pkg/feature/api/segment_user.go
pkg/feature/api/tag.go
pkg/notification/api/api.go
pkg/notification/api/subscription.go
pkg/push/api/api.go
pkg/role/role.go
pkg/role/role_test.go

Reverts bucketeer-io/bucketeer#651

revert: chore replace account v1 to v2 when checking the role

---

test/e2e/account/account_test.go

- This PR adds a process to create an account before executing ListAccountsV2 API.

test: fix list account test

---

docs/rfcs/serverless-for-background-services.md

This PR will add an RFC (Request for Comments) that demonstrates how to implement serverless architecture for background services.
Reference: https://github.com/bucketeer-io/bucketeer/issues/612

docs: reduce costs in the background services rfc

---

manifests/bucketeer/charts/batch/templates/cronjob.yaml
manifests/bucketeer/charts/batch/values.yaml

part of https://github.com/bucketeer-io/bucketeer/issues/671

chore(manifests): add mau partition creator cronjob

---

test/e2e/feature/feature_flag_trigger_test.go

Fixes https://github.com/bucketeer-io/bucketeer/issues/682

test: fix cannot delete or update a parent row when deleting e2e data

---

ui/web-v2/apps/admin/src/components/ActionMenu/index.tsx
ui/web-v2/apps/admin/src/components/ExperimentList/index.tsx
ui/web-v2/apps/admin/src/pages/experiment/index.tsx

Fixes https://github.com/bucketeer-io/bucketeer/issues/691

fix(ui): show stop experiment in experiment list action

---

.github/workflows/push-image.yaml

Fixes https://github.com/bucketeer-io/bucketeer/issues/692

fix: dispatch workflow fails if commit message contains multi-lines

---

ui/web-v2/apps/admin/src/components/APIKeyList/index.tsx
ui/web-v2/apps/admin/src/components/ExperimentList/index.tsx
ui/web-v2/apps/admin/src/components/FeatureHeader/index.tsx
ui/web-v2/apps/admin/src/components/FeatureList/index.tsx
ui/web-v2/apps/admin/src/components/GoalList/index.tsx
ui/web-v2/apps/admin/src/components/ProjectList/index.tsx
ui/web-v2/apps/admin/src/pages/feature/experiments.tsx
ui/web-v2/apps/admin/src/pages/feature/variations.tsx
ui/web-v2/apps/admin/src/utils/date.ts

Fixes https://github.com/bucketeer-io/bucketeer/issues/696

chore(ui): unify date format between english and japanese

---

pkg/autoops/storage/v2/auto_ops_rule.go
pkg/autoops/storage/v2/progressive_rollout.go
pkg/autoops/storage/v2/sql/auto_ops_rule/insert_auto_ops_rule.sql
pkg/autoops/storage/v2/sql/auto_ops_rule/select_auto_ops_rule.sql
pkg/autoops/storage/v2/sql/auto_ops_rule/select_auto_ops_rules.sql
pkg/autoops/storage/v2/sql/auto_ops_rule/update_auto_ops_rule.sql
pkg/autoops/storage/v2/sql/ops_progressive_rollout/count_ops_progressive_rollouts.sql
pkg/autoops/storage/v2/sql/ops_progressive_rollout/delete_ops_progressive_rollout.sql
pkg/autoops/storage/v2/sql/ops_progressive_rollout/insert_ops_progressive_rollout.sql
pkg/autoops/storage/v2/sql/ops_progressive_rollout/select_ops_progressive_rollout.sql
pkg/autoops/storage/v2/sql/ops_progressive_rollout/select_ops_progressive_rollouts.sql
pkg/autoops/storage/v2/sql/ops_progressive_rollout/update_ops_progressive_rollout.sql

Fixes https://github.com/bucketeer-io/bucketeer/issues/719
- Moved the SQL query hard code to the SQL files in the auto ops service

refactor: move auto ops queries to sql files

---

pkg/auth/api/api.go

- Change to use the GetMyOrganizationsByEmail() function instead of the old GetMeV2ByEmail() function when issuing IDToken.
- This change allows the GetMeV2ByEmail() function to be removed.

chore: update generate token process

---

ui/web-v2/apps/admin/src/assets/lang/en.json
ui/web-v2/apps/admin/src/assets/lang/ja.json
ui/web-v2/apps/admin/src/components/FilterPopover/index.tsx
ui/web-v2/apps/admin/src/components/Select/index.tsx
ui/web-v2/apps/admin/src/lang/messages.ts

Fixes https://github.com/bucketeer-io/bucketeer/issues/722

chore(ui): enable the search feature for the filter options in the search filter

---

pkg/feature/storage/v2/segment.go

Fixes https://github.com/bucketeer-io/bucketeer/issues/738

fix: unknown column 'is_in_use_status' in 'having clause'

---

.github/workflows/push-image.yaml

Fixes https://github.com/bucketeer-io/bucketeer/issues/740
CI:
https://github.com/bucketeer-io/bucketeer/actions/runs/7691884309

ci: fix need to provide valid JSON payload error when sending slack notification

---

pkg/environment/api/project.go
pkg/environment/api/project_test.go

- I replaced the old account API with the new API while creating a new org, project, and account.

fix: unable create trial project

---

pkg/account/storage/v2/account.go
pkg/account/storage/v2/admin_account.go
pkg/account/storage/v2/api_key.go
pkg/account/storage/v2/storage.go

Fixes https://github.com/bucketeer-io/bucketeer/issues/754
This fixes the account E2E tests failing randomly.

fix: invalid mysql connection when using transaction

---

proto/Makefile
proto/event/client/event.pb.go
proto/event/domain/event.pb.go
proto/event/domain/localized_message.pb.go
proto/event/service/feature.pb.go
proto/event/service/segment.pb.go
proto/event/service/user.pb.go
proto/notification/sender/notification.pb.go
proto/notification/sender/notification_event.pb.go

There are some proto directories with subdirectories. Those didn't match the condition and weren't removed.
- Fixed the remove code
- Updated the proto subdirectories

fix: omitempty not being removed in the proto subdirectories

---

pkg/autoops/api/api_test.go
pkg/feature/api/api_test.go
pkg/push/api/api_test.go
pkg/role/role.go
pkg/token/idtoken.go

part of https://github.com/bucketeer-io/bucketeer/issues/774

refactor: remove isAdmin function

---

pkg/auth/api/api.go

Fixes https://github.com/bucketeer-io/bucketeer/issues/795

fix: system admin does not have access to resources

---

pkg/feature/api/feature.go
test/e2e/feature/feature_test.go

Part of https://github.com/bucketeer-io/bucketeer/pull/712
This is the last change on the server side. The rest will be made on the admin console.
- Stop the progressive rollout when the user disabled a flag
- Added e2e test for the case above
---
This pull request primarily focuses on the `pkg/feature/api/feature.go` and `test/e2e/feature/feature_test.go` files, introducing changes to manage the progressive rollout of features. It adds functionality to stop the progressive rollout if a `DisableFeatureCommand` is detected, and includes tests to verify this behavior.
Key Changes:
**1. Codebase changes:**
* [`pkg/feature/api/feature.go`](diffhunk://#diff-2d0a2c8153246509abb80eca89b6ca25f95f7ea8e75640dae22408489b8b0eafR30): Imported the `v2ao` package to manage progressive rollouts.
* …

chore: stop progressive when disabling a flag

---

pkg/gateway/api/api_grpc.go

Currently, the single flight implementation is only being used when there is no cache for the API key. Like the [getFeatures](https://github.com/bucketeer-io/bucketeer/blob/main/pkg/gateway/api/api_grpc.go#L617-L653), it should also use the single flight when getting the key from the cache to reduce the load in the cacher.
- Changed to use single flight when getting the API key from the cache
- Small refactoring
---
This pull request involves changes in the `pkg/gateway/api/api_grpc.go` file to enhance the handling of environment API keys. The primary changes include a reordering of operations within the `getEnvironmentAPIKey` function, the creation of a new `putEnvironmentAPIKeyCache` function, and the removal of a redundant return statement in `getEnvironmentAPIKey`.
Here are the most …

perf: change to get api key from cache using single flight

---

pkg/batch/jobs/notification/domain_event_informer.go

fix: reuse errgroup in domain event informer

---

pkg/pubsub/puller/rate_limited_puller.go

fix: nack msg when ctx is done

---

pkg/eventpersister/persister/persister.go

Fixes https://github.com/bucketeer-io/bucketeer/issues/828

fix: persister fails due to nil pointer

---

pkg/eventpersister/persister/persister.go

I've refactored the code to isolate the cache-writing logic from the `batch` function, preventing it from executing in multiple workers. Additionally, I've relocated the cache from a local variable to a struct member to ensure each worker operates using the same cache.
----
This pull request introduces changes to the `pkg/eventpersister/persister/persister.go` file, primarily focused on improving the handling of the feature flag last-used cache. The changes include the introduction of a Mutex for synchronization, moving the cache from a local variable to a struct member, and restructuring the cache update and write operations.
The most important changes are:
Cache Management:
* [`import (`](diffhunk://#diff-ad00cb580cd315d8619de51e511dc06052ace57d6146c30b60366e3a97b56d6cR21): Imported the …

refactor: isolate the cache-writing logic from the batch function 

---

ui/web-v2/apps/admin/src/pages/admin/environment/index.tsx
ui/web-v2/apps/admin/src/pages/admin/projects/index.tsx

The update page must use the ID instead of the URL code.

fix(ui): admin update pages using using url code instead of id

---

ui/web-v2/apps/admin/src/components/AdminNotificationUpdateForm/index.tsx
ui/web-v2/apps/admin/src/components/GoalUpdateForm/index.tsx
ui/web-v2/apps/admin/src/components/NotificationUpdateForm/index.tsx
ui/web-v2/apps/admin/src/components/PushUpdateForm/index.tsx
ui/web-v2/apps/admin/src/pages/account/index.tsx
ui/web-v2/apps/admin/src/pages/admin/environment/index.tsx
ui/web-v2/apps/admin/src/pages/admin/notification/index.tsx
ui/web-v2/apps/admin/src/pages/admin/projects/index.tsx
ui/web-v2/apps/admin/src/pages/apiKey/index.tsx
ui/web-v2/apps/admin/src/pages/goal/index.tsx
ui/web-v2/apps/admin/src/pages/notification/index.tsx
ui/web-v2/apps/admin/src/pages/push/index.tsx
ui/web-v2/apps/admin/src/pages/segment/index.tsx

Fixes https://github.com/bucketeer-io/bucketeer/issues/838

fix(ui): open update overlay when click on the url link

---

ui/web-v2/apps/admin/src/components/FeatureAutoOpsRulesForm/index.tsx

fix(ui): kill switch operation's start status is incorrect

---

pkg/eventpersisterdwh/persister/persister.go
pkg/eventpersisterops/persister/persister.go

Many places are using `continue` when an error occurs. By placing the reset interval in the last when an error occurs, it stops checking whether to subscribe or unsubscribe to PubSub.
This also could be related to flaky e2e tests using the event persisters.

fix: pubsub subscription check stops working when an error occurs

---

ui/web-v2/apps/admin/src/components/ExperimentAddForm/index.tsx
ui/web-v2/apps/admin/src/pages/admin/notification/index.tsx
ui/web-v2/apps/admin/src/pages/admin/projects/index.tsx
ui/web-v2/apps/admin/src/pages/experiment/index.tsx
ui/web-v2/apps/admin/src/pages/goal/index.tsx
ui/web-v2/apps/admin/src/pages/notification/index.tsx
ui/web-v2/apps/admin/src/pages/push/index.tsx

fix: flag list in the experiment creation page shouldn't list archived flags

---

test/e2e/eventcounter/eventcounter_test.go
test/e2e/gateway/api_grpc_test.go

Depending on the time this test runs, there might not be any feature flag in the cache
So, we wait until the caches are updated. Usually, one minute.

test: fix flaky e2e test in the api-gateway

---

docs/rfcs/batch-service-pubsub-improvement.md

This PR proposes a new architecture for multiple GCP pub-sub.

docs: multi pub-sub arch in barch service

---

ui/web-v2/apps/admin/src/components/FeatureConfirmDialog/index.tsx
ui/web-v2/apps/admin/src/components/FeatureTargetingForm/index.tsx
ui/web-v2/apps/admin/src/pages/feature/targeting.tsx

Fixes https://github.com/bucketeer-io/bucketeer/issues/895

fix(ui): showing wrong message in the confirm dialog on targeting page

---

pkg/feature/segmentpersister/persister.go
pkg/feature/segmentpersister/persister_test.go
pkg/feature/storage/v2/segment_user.go

Currently, to upsert 40k (2MB) users takes 60-90 seconds.
Inserting multiple rows in a single query takes only 2-5 seconds.
We also should limit the maximum rows in the single query. Otherwise, the performance could be worse than now.
So, I implemented a batch logic to limit the rows per query. 1000 seems a sweet spot.
Start at `1711680294` and finished at `1711680372` (78 seconds)
Start at `1711679321` and finished at `1711679327` (6 seconds)
---
This pull request in `pkg/feature` includes changes to improve error handling, optimize data persistence, and refactor code for better readability and performance. The most important changes include updating the segment status to failed when an error occurs in `handleEvent`, returning an error instead of nil in `persistSegmentUsers`, adding a …

perf: upsert segment user query

---

.github/workflows/push-image.yaml

part of https://github.com/ca-dp/bucketeer-issue/issues/1

ci: add action job to run node sdk e2e

---

manifests/bucketeer/charts/batch/values.dev.yaml

This PR will add subscribers config in batch service for dev container.

chore: add subscribers config for dev container

---

.gitignore
go.mod
go.sum
proto/go.mod
proto/go.sum

Part of https://github.com/bucketeer-io/bucketeer/issues/921

chore: implement proto dir as go module

---

pkg/gateway/api/api.go
pkg/gateway/api/api_grpc.go

Part of https://github.com/bucketeer-io/bucketeer/pull/923

chore: revert check environment role condition

---

manifests/bucketeer/charts/batch/templates/_helpers.tpl
manifests/bucketeer/charts/batch/templates/deployment.yaml
manifests/bucketeer/charts/batch/values.dev.yaml
manifests/bucketeer/charts/batch/values.yaml
pkg/batch/cmd/server/server.go

This PR will add authentication check for `batch` service.
After added authentication, the request made to batch service should be the following:
```shell
curl POST -vvv -k https://bucketeer.io/bucketeer.batch.BatchService/ExecuteBatchJob -H "authorization: bearer $TOKEN" -H "Content-Type: application/json" -d '{"job": "ApiKeyCacher"}'
```

feat: batch service authentication

---

pkg/gateway/api/api.go
pkg/gateway/api/api_grpc.go
pkg/gateway/api/metrics.go

fixes https://github.com/bucketeer-io/bucketeer/issues/927

feat: add requst counter metrics to api-gateway

---

evaluation/evaluation.go
evaluation/evaluation_test.go
go.mod
pkg/gateway/api/api_test.go

fixes https://github.com/bucketeer-io/bucketeer/issues/968

fix: evaluation fails

---

evaluation/evaluation.go
pkg/feature/domain/feature.go
pkg/feature/domain/feature_test.go

part of https://github.com/bucketeer-io/bucketeer/issues/963

chore: add function to return other features to depends on the feature

---

evaluation/evaluation.go

part of https://github.com/bucketeer-io/bucketeer/issues/963

refactor: replace prerequisite with FeatureIDsDependsOn to express feature dependences

---

pkg/feature/api/feature_test.go
pkg/feature/api/validation.go

part of https://github.com/bucketeer-io/bucketeer/issues/963

chore: add validation of feature dependency rule

---

pkg/batch/storage/v2/sql/count_auto_ops_rules.sql

Fix https://github.com/bucketeer-io/bucketeer/issues/997

fix: including archived features in the count query

---

pkg/feature/domain/feature.go
pkg/feature/domain/feature_test.go

part of https://github.com/bucketeer-io/bucketeer/issues/963

fix: missing rule clause validation

---

.github/.devcontainer/Dockerfile
.github/.devcontainer/devcontainer.json
.github/.devcontainer/first-run-notice.txt
.github/workflows/devcontainer-image-build.yaml

I'm configuring the dev container building conditions to build it automatically so we don't forget.

ci: update devcontainer building conditions

---

docs/rfcs/multi-schedules.md

This PR adds RPC documentation for implementing the multi schedule. : #885

docs: add rfc for multi schedule

---

.devcontainer/devcontainer.json

the same format tools as CI workflow.

chore: set go format settings to devcontainer

---

pkg/gateway/api/api_grpc_test.go

part of https://github.com/bucketeer-io/bucketeer/issues/904

test: add get feature test

---

pkg/batch/subscriber/processor/push_sender.go
pkg/batch/subscriber/processor/push_sender_test.go

part of https://github.com/bucketeer-io/bucketeer/issues/804

chore: run push sender when feature updated event is created

---

Makefile

chore: add generate all command to makefile

---

ui/web-v2/src/components/AddProgressiveRolloutOperation/index.tsx
ui/web-v2/src/pages/feature/formSchema.ts

Fixes Issue #1085 
Changes:
- Resolved the Add Auto Ops disabled button issue
- Fixed Re-rendering Issue in the "Add Progressive Rollout" component.

fix(ui): can't create an auto operation

---

ui/web-v2/src/pages/segment/formSchema.ts

Fix #1092 
- Make list of user ids optional

fix(ui): can't create a user segment #1092

---

ui/web-v2/src/components/SegmentList/index.tsx

Part of https://github.com/bucketeer-io/bucketeer-docs/issues/109

chore(ui): update segment documentation link

---

pkg/auth/api/api.go
pkg/token/token.go

Forgot to set the `issueAt` in the token.

chore: set the token issue at field

---

migration/mysql/20240708065726_update_audit_log_table.sql
migration/mysql/atlas.sum
pkg/auditlog/storage/v2/audit_log.go
pkg/auditlog/storage/v2/audit_log_test.go
pkg/auditlog/storage/v2/sql/auditlog/insert_audit_log_v2.sql
pkg/auditlog/storage/v2/sql/auditlog/select_audit_log_v2.sql

part of https://github.com/bucketeer-io/bucketeer/issues/804

chore: add entity data to auditlog storage

---

ui/web-v2/src/components/FeatureTargetingForm/index.tsx

Fixes https://github.com/bucketeer-io/bucketeer/issues/1106

chore: make feature flags in targeting rule searchable

---

.github/workflows/push-image.yaml

Part of https://github.com/bucketeer-io/bucketeer/pull/1096

ci: remove web-v2 job from push image workflow

---

pkg/feature/api/feature.go

This PR enables UpdateFeature API to update archived features.

fix: cannot update archived features

---

Makefile
tools/dev/Makefile

This pull request will increase the resource limits upon starting Minikube. 
Additionally, it will verify if the user has initiated Minikube more than twice; if is, the start process will be skipped.

chore: dev container performance

---

pkg/autoops/api/progressive_rollout.go
pkg/autoops/api/progressive_rollout_operation.go
pkg/autoops/api/progressive_rollout_test.go

Fixes https://github.com/bucketeer-io/bucketeer/issues/1070

chore: call update feature api at progressive rollout execution

---

pkg/auth/api/api.go

I found an error when creating the demo environment in the dev environment.
Because we already have a project with the `demo` ID, it fails with an `Already Exists` error, not proceeding with the environment and account creation.
I fixed it only to stop the process if it gets an error different than not found or already exists errors.

fix: demo environment not being created

---

ui/web-v2/src/components/OperationAddUpdateForm/index.tsx

Fix https://github.com/bucketeer-io/bucketeer/issues/1135

fix(ui): cannot create an enable auto operation

---

ui/web-v2/src/components/FeatureAutoOpsRulesForm/index.tsx

Fix https://github.com/bucketeer-io/bucketeer/issues/1138

chore(ui): change on/off label for the the schedule operation

---

pkg/account/api/admin_account.go
pkg/account/api/admin_account_test.go
pkg/auth/api/api.go

To improve access security, we must also check the user account status when generating the access token and when the `GetMe` API is called. Currently, we only check if the account exists.
----
This pull request introduces changes to enhance the account status check and error handling in the `AccountService` and `AuthService`. The most important changes include the addition of `checkAccountStatus` method in both services, changes to `GetMe` method in `AccountService`, and updates to the corresponding test cases.
Account status check:
* [`pkg/account/api/admin_account.go`](diffhunk://#diff-1097fbb3548177580d8c5e170cc44b5cb9db843fc88c1e618802ad74122cfc95R66-R72): Added a new method `checkAccountStatus` to validate if the user account is enabled. This method is now called within the `GetMe` …

chore: check account status when generating access token and GetMe api

---

pkg/auth/api/api.go

System admin accounts have access to all organizations but are registered only in the system admin organization.
So, to avoid false errors, we ignore them if the account wasn't found in non-system admin organizations.

chore: remove not found log from check account status

---

pkg/batch/subscriber/processor/evaluation_events_evaluation_count_event_persister.go

Fix https://github.com/bucketeer-io/bucketeer/issues/1170

fix: pubsub message not being acknowledged when the reason is nil

---

migration/mysql/20240815043128_update_auto_ops_rule_table.sql
migration/mysql/atlas.sum

Part of https://github.com/bucketeer-io/bucketeer/pull/1179

chore(migration): set default value for triggered_at column

---

migration/mysql/20240815101256_update_auto_ops_rule_table.sql
migration/mysql/atlas.sum

Relate https://github.com/bucketeer-io/bucketeer/pull/1179

chore: delete triggeredAt for auto_ops_role table

---

manifests/bucketeer/charts/subscriber/templates/envoy-configmap.yaml

Fix https://github.com/bucketeer-io/bucketeer/issues/1203

fix: unimplemented api errror in the subscriber svc

---

pkg/feature/api/feature.go

If the experience was filtered by criteria, an Unknown Error occurred when searching by ID or name.

fix: column 'id' in where clause is ambiguous when searching flag

---

pkg/account/api/search_filter.go
pkg/account/api/search_filter_test.go

Fix https://github.com/bucketeer-io/bucketeer/issues/1236
When a system admin account logs in to a non-system admin organization, its account doesn't exist in that organization, so when the server tries to create/update/delete, it fails because it doesn't find the account.
So, I fixed it to check if it is a system admin. If so, it will replace the organization ID with the system admin organization ID to save it correctly.
When getting the console account via **[GetMe](https://github.com/bucketeer-io/bucketeer/blob/main/pkg/account/api/admin_account.go#L140)** API, it already replaces the organization ID, so no need to change anything.

fix: system admin search filter not being updated

---

ui/web-v2/src/components/FeatureAddForm/index.tsx

fix: unable to create boolean type feature flag

---

pkg/environment/api/organization.go

Fix https://github.com/bucketeer-io/bucketeer/issues/1304
When changing the Organization's owner, we must update the old owner's role because there can only be one owner per 
Organization.

fix: owner organization role not being updated

---

ui/web-v2/src/components/FeatureList/index.tsx
ui/web-v2/src/storage/searchFilterDialog.ts

Show the search filter only once by checking a flag in local storage.

feat(ui): show search filter only once

---

evaluation/go/user_evaluations.go

Fixes https://github.com/bucketeer-io/bucketeer/issues/1362

chore: change user evaluations id to use feature updated at

---

pkg/subscriber/processor/evaluation_events_evaluation_count_event_persister.go

Fixes https://github.com/bucketeer-io/bucketeer/issues/1368

perf: change to save user and event counts in one request

---

pkg/account/api/api.go
pkg/api/api/api.go
pkg/api/api/api_grpc.go
pkg/auditlog/api/api.go
pkg/autoops/api/api.go
pkg/autoops/api/progressive_rollout.go
pkg/cli/app.go
pkg/environment/api/api.go
pkg/eventcounter/api/api.go
pkg/experiment/api/api.go
pkg/feature/api/api.go
pkg/feature/api/feature.go
pkg/feature/api/flag_trigger.go
pkg/feature/api/segment.go
pkg/feature/api/segment_user.go
pkg/metrics/metrics.go
pkg/notification/api/api.go
pkg/pubsub/pubsub.go
pkg/push/api/api.go
pkg/rest/server.go
pkg/rpc/server.go
pkg/subscriber/on_demand_subscriber.go
pkg/subscriber/processor/domain_event_informer.go
pkg/subscriber/processor/evaluation_events_evaluation_count_event_persister.go
pkg/subscriber/processor/events_dwh_persister.go
pkg/subscriber/processor/events_ops_persister.go
pkg/subscriber/processor/push_sender.go
pkg/subscriber/processor/user_event_persister.go
pkg/subscriber/subscriber.go

Fix https://github.com/bucketeer-io/bucketeer/issues/1414

fix: info and error log level

---

pkg/api/api/api_grpc.go
pkg/api/api/metrics_event.go
pkg/subscriber/processor/auditlog_persister.go
pkg/subscriber/processor/evaluation_events_evaluation_count_event_persister.go
pkg/subscriber/processor/events_dwh_persister.go
pkg/subscriber/processor/events_ops_persister.go
pkg/subscriber/processor/segment_user_persister.go
pkg/subscriber/processor/user_event_persister.go

Part of https://github.com/bucketeer-io/bucketeer/issues/1414

chore: remove unnecessary logs

---

ui/web-v2/src/components/DebuggerResult/index.tsx

Fix https://github.com/bucketeer-io/bucketeer/issues/1423

feat(ui): add variation id to the debugger results page

---

test/e2e/environment/environment_v2_test.go

CreateEnvironment no longer return environment, should call get environment to verify again

test: fix e2e environment should call get environment API again

---

pkg/api/api/api_grpc.go

Fix https://github.com/bucketeer-io/bucketeer/issues/1552

fix: flag not found when using dependency flag in targeting rule

---

README.md

- add myself to contributors list

docs: add new contributor

---

pkg/feature/api/flag_trigger.go
pkg/feature/api/flag_trigger_test.go

This pull request focuses on refactoring the `FeatureService` to use a new transaction handling method and updating the corresponding tests. The main changes include replacing the old transaction method with the new `RunInTransactionV2` method and updating the storage calls to use the `flagTriggerStorage` directly.
Relate #1549
Part of https://github.com/bucketeer-io/bucketeer/issues/1474

refactor: refactor transaction processing regarding FlagTrigger storage in Feature package

---

test/e2e/tag/tag_test.go

```sh
make e2e
go test -v ./test/e2e/tag/... -args \
-web-gateway-addr=web-gateway.bucketeer.io \
-web-gateway-port=443 \
-web-gateway-cert=/workspaces/bucketeer/tools/dev/cert/tls.crt \
-api-key=/workspaces/bucketeer/tools/dev/cert/api_key_client \
-api-key-server=/workspaces/bucketeer/tools/dev/cert/api_key_server \
-gateway-addr=api-gateway.bucketeer.io \
-gateway-port=443 \
-gateway-cert=/workspaces/bucketeer/tools/dev/cert/tls.crt \
-service-token=/workspaces/bucketeer/tools/dev/cert/service-token \
-environment-id=e2e \
-organization-id=default \
-test-id=
=== RUN   TestUpsertAndListTag
=== PAUSE TestUpsertAndListTag
=== RUN   TestDeleteTag
=== PAUSE TestDeleteTag
=== CONT  TestUpsertAndListTag
=== CONT  TestDeleteTag
--- PASS: TestDeleteTag (0.06s)
--- PASS: TestUpsertAndListTag …
```

test: fix index out of range when running tag e2e tests

---

pkg/api/api/api_grpc_test.go
pkg/api/api/grpc_validation.go
pkg/api/api/grpc_validation_test.go
pkg/api/api/metrics.go

Reverts bucketeer-io/bucketeer#1624
Some e2e tests fail becase of this change..🙇

revert: validate events from the sdk in api gateway

---

ui/dashboard/src/components/pagination/index.tsx
ui/dashboard/src/pages/api-keys/collection-loader/index.tsx
ui/dashboard/src/pages/experiments/collection-loader/index.tsx
ui/dashboard/src/pages/feature-flags/collection-loader/index.tsx
ui/dashboard/src/pages/goals/collection-loader/index.tsx
ui/dashboard/src/pages/members/collection-loader/index.tsx
ui/dashboard/src/pages/notifications/collection-loader/index.tsx
ui/dashboard/src/pages/organization-details/members/collection-loader/index.tsx
ui/dashboard/src/pages/organizations/collection-loader/index.tsx
ui/dashboard/src/pages/project-details/environments/collection-loader/index.tsx
ui/dashboard/src/pages/projects/collection-loader/index.tsx
ui/dashboard/src/pages/pushes/collection-loader/index.tsx
ui/dashboard/src/pages/user-segments/collection-loader/index.tsx

The total count is not showing on the left bottom list page when there is no pagination.
Fix #1640

fix(ui/dashboard): total count is not showing on the bottom list page

---

ui/dashboard/src/pages/api-keys/api-key-modal/edit-api-key-modal/index.tsx

The list page shows which environment the key belongs to, but on the update page, the environment isn't shown in the drop-down menu, which I think is the issue.
Fix #1628

fix(ui/dashboard): can't update api key

---

ui/dashboard/src/pages/members/collection-layout/data-collection.tsx
ui/dashboard/src/pages/notifications/collection-layout/data-collection.tsx
ui/dashboard/src/pages/user-segments/collection-layout/data-collection.tsx

Pages affected (List page)
Slack
Members
User Segments
Need to check other pages.
Fix #1651

fix(ui/dashboard): date column is not showing the full date when passing the mouse over

---

ui/dashboard/src/elements/collection/collection-empty/index.tsx
ui/dashboard/src/pages/experiments/collection-loader/index.tsx

Some pages, such as the Member list page, are, showing the background color button incorrectly. It should be white with a purple border.
Check all other pages.
Fix #1646

fix(ui/dashboard): the clear button is different from the design

---

ui/dashboard/public/locales/en/common.json
ui/dashboard/public/locales/ja/common.json
ui/dashboard/src/components/dropdown/index.tsx
ui/dashboard/src/pages/feature-flags/flags-modal/filter-flag-modal/index.tsx

Some environments have many maintainers or tags, which it is annoying to scroll down to find the target item.
Fix #1633

chore(ui/dashboard): allow searching when selecting the filter value

---

migration/mysql/20250331135358_update_feature_last_used_info_table.sql
migration/mysql/atlas.sum

Fix https://github.com/bucketeer-io/bucketeer/issues/1665

perf: improve list feature flags query latency

---

pkg/api/api/api.go
pkg/api/api/api_grpc.go
pkg/api/api/api_grpc_test.go
pkg/api/api/metrics_event.go
pkg/autoops/api/progressive_rollout.go
pkg/subscriber/processor/evaluation_events_evaluation_count_event_persister.go

Related to https://github.com/bucketeer-io/bucketeer/pull/1566

chore: remove unnecessary error logs in the api svc

---

ui/dashboard/src/auth/auth-context.tsx
ui/dashboard/src/auth/utils.ts
ui/dashboard/src/components/navigation/my-projects.tsx
ui/dashboard/src/components/navigation/switch-organization.tsx

The user gets logged out when switching organization due to not found environment error.
Fix #1673

fix(ui/dashboard): user gets logged out when switching organizations

---

test/e2e/auditlog/audit_log_test.go

It fails randomly with `upstream request timeout` error.
I'm implementing a retry logic in the test, just like other places, to improve this.

test: fix flaky list audit logs e2e test

---

ui/dashboard/src/pages/audit-logs/collection-layout/audit-log-item.tsx
ui/dashboard/src/pages/audit-logs/collection-layout/audit-log-title.tsx
ui/dashboard/src/pages/audit-logs/elements/audit-logs-modal/audit-log-details.tsx
ui/dashboard/src/pages/audit-logs/utils.ts

Updated the link in the entity name

fix(ui/dashboard): audit log link id

---

ui/dashboard/src/pages/api-keys/api-key-modal/add-api-key-modal/index.tsx

fix: wrong key role when creating API key
Fix #1695

fix(ui/dashboard): wrong key role when creating API key

---

ui/dashboard/src/pages/debugger/debugger-flags.tsx
ui/dashboard/src/pages/feature-flags/collection-layout/elements/index.tsx

The add flag button is not disabling even after adding all the flags available from the list.
Fix #1764

fix(ui/dashboard): showing wrong variations colors in the tooltip

---

pkg/feature/api/tag.go
pkg/feature/api/tag_test.go
pkg/tag/api/api.go
pkg/tag/api/api_test.go
pkg/tag/storage/mock/tag.go
pkg/tag/storage/sql/count_tags.sql
pkg/tag/storage/sql/select_tags.sql
pkg/tag/storage/tag.go
pkg/tag/storage/tag_test.go

Reverts https://github.com/bucketeer-io/bucketeer/pull/1774

revert: change ListTags to utilize ListOptions

---

pkg/notification/sender/sender.go
pkg/notification/sender/sender_test.go

When there are multiple subscriptions, and one of them fails due to a flag not found error, it returns an error, ignoring the other subscriptions.

fix: slack notification not being in some cases

---

ui/dashboard/src/@api/push/push-delete.ts
ui/dashboard/src/@locales/en/common.json
ui/dashboard/src/@locales/en/message.json
ui/dashboard/src/@locales/en/table.json
ui/dashboard/src/@locales/ja/common.json
ui/dashboard/src/@locales/ja/message.json
ui/dashboard/src/@locales/ja/table.json
ui/dashboard/src/pages/pushes/collection-layout/data-collection.tsx
ui/dashboard/src/pages/pushes/page-loader.tsx
ui/dashboard/src/pages/pushes/types.ts

Fix https://github.com/bucketeer-io/bucketeer/issues/1825

feat(ui/dashboard): implement delete FCM notifications

---

pkg/rpc/gateway/gateway.go

fix #1862 
After thorough investigation of our metrics collection architecture, we determined that implementing these TODOs would create duplicate metrics and is unnecessary.
So fix comment and add `NOTE`.
- Do not implement the TODO - Additional metrics at the gRPC-Gateway layer would create unnecessary
duplication
- Update code comments to explain why metrics aren't needed

chore: remove TODO comments about adding metrics in gRPC-Gateway error handling

---

ui/dashboard/src/auth/auth-context.tsx
ui/dashboard/src/components/navigation/user-profile.tsx
ui/dashboard/src/i18n/utils.ts

fix(ui/dashboard): update language settings when updating user profile

---

pkg/api/api/api_grpc.go
pkg/api/api/api_grpc_test.go
pkg/api/api/grpc_validation.go
pkg/api/api/grpc_validation_test.go
pkg/api/api/validation_test.go
pkg/api/cmd/server.go

Fix https://github.com/bucketeer-io/bucketeer/issues/1893

chore: change event timestamp validation from 1 day to 31 days

---

manifests/bucketeer/charts/web/templates/env-js-configmap.yaml
manifests/bucketeer/charts/web/values.dev.yaml
manifests/bucketeer/charts/web/values.yaml

The API endpoint will be shown in the console's help menu.

chore: add api endpoint env var for the web console

---

ui/dashboard/src/pages/experiment-details/collection-loader/settings/index.tsx
ui/dashboard/src/pages/experiments/experiments-modal/experiment-create-update/index.tsx

fix(ui/dashboard): flag not showing in the flag list when creating experiments

---

ui/dashboard/src/constants/documentation-links.ts
ui/dashboard/src/pages/api-keys/page-content.tsx
ui/dashboard/src/pages/audit-logs/page-content.tsx
ui/dashboard/src/pages/experiments/page-content.tsx
ui/dashboard/src/pages/feature-flag-details/history/index.tsx
ui/dashboard/src/pages/feature-flags/page-content.tsx
ui/dashboard/src/pages/goals/page-content.tsx
ui/dashboard/src/pages/members/page-content.tsx
ui/dashboard/src/pages/notifications/page-content.tsx
ui/dashboard/src/pages/organization-details/members/index.tsx
ui/dashboard/src/pages/organization-details/projects/index.tsx
ui/dashboard/src/pages/organizations/page-content.tsx
ui/dashboard/src/pages/project-details/environments/page-content.tsx
ui/dashboard/src/pages/projects/page-content.tsx
ui/dashboard/src/pages/pushes/page-content.tsx
ui/dashboard/src/pages/user-segments/page-content.tsx

fix(ui/dashboard): update document links for the pages

---

migration/mysql/20250711131250_update_indexes.sql
migration/mysql/atlas.sum

Fix https://github.com/bucketeer-io/bucketeer/issues/1986

perf: improving query latency when retriving user's organizations

---

pkg/feature/api/segment_user.go

Remove validation that prevents segment user list updates when in use.
fix #2000

chore: remove segment IsInUseStatus validation

---

.github/.devcontainer/Dockerfile

build(dev-container): update libncurses dependency from libncurses5 to libncurses6

---

pkg/environment/api/organization.go
pkg/environment/api/organization_test.go

Fix https://github.com/bucketeer-io/bucketeer/issues/2022
- Fixed user role not updating when changing the organization owner
- Added validation not to allow an admin member to change an owner

fix: user role not updating when changing the organization owner

---

pkg/account/api/account.go

chore: environment members can now view admin accounts

---

pkg/autoops/api/progressive_rollout.go
pkg/autoops/api/progressive_rollout_test.go

The reason was a race condition between the get and update feature interface using different contexts.
I fixed the race condition, but I had to add a verification to determine whether to proceed when updating the flag because the triggeredAt is updated in the same transaction as the flag update, so if the flag update fails, it will roll back the triggeredAt, causing this infinite error loop.
So, if the flag object is already updated, it will skip the flag update process to avoid issues by just updating the progressive rollout status.

fix: unexpected affected rows error when triggering progressive rollout
