.github/workflows/pr-ui-web.yaml
ui/web-v2/Makefile

The current CI for the `ui/web-v2` pull request runs on the Argo workflow. Because the CI website is for internal use only, I'm migrating it from Argo to GitHub Actions so everyone can see the result logs.
Results from the action workflow.
https://github.com/bucketeer-io/bucketeer/actions/runs/3172891781

ci: add action workflow to valid pull request for ui/web-v2

---

.github/workflows/cla.yaml

This makes it possible to sign the CLA for all contributors before merging a PR.
Before merging this PR, there are two requirements the followings.

ci: add the CLA job for contributors to sign it

---

pkg/feature/domain/feature.go
pkg/feature/domain/feature_test.go

When the feature flag type is JSON, and the JSON value is an array, it fails because it tries to unmarshal into a map.

fix: json cannot unmarshal array while trying to create a feature flag

---

.github/workflows/pr-title-validation.yaml
.github/workflows/publish_chart.yaml

This is a just suggestion to be more secure.
This might be helpful when a release tag is overridden or deleted suddenly, especially for un-official actions.
And I also highly recommend configuring `Actions permissions` to allow all actions that this project wanna use explicitly if you have not configured it yet.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-select-actions-and-reusable-workflows-to-run

ci: use a sha as an action's ref instead of a release tag

---

ui/web-v2/apps/admin/src/pages/feature/formSchema.ts

The feature flag name is a required field, but it wasn't being checked.

fix(ui/web-v2): feature flag name not being checked

---

pkg/locale/BUILD.bazel
pkg/locale/localizer.go

- Removed `go_embed_data` rule from `pkg/locale/BUILD.bazel`.
- Introduced //go:embed to read files instead.
- We need //go:embed to replace Bazel with `go build`.
- Even if this PR is merged, it can be still built with both `bazelisk` and `go build`.

build: remove go_embed_data rule

---

.github/workflows/pr-ui-web.yaml
ui/web-v2/Makefile

Because I added the [external](https://github.com/bucketeer-io/bucketeer/pull/25) `google/api` import files, the CI for the web was failing.

build: fix not found error while generating proto web files

---

.gitignore
Makefile

- added `go build` and `go test` commands to Makefile.
- `make build-go-apps` creates the executable files (such as `account`, `auditlog`, ... ) in `./bin` directory.

build: add go build,test commands

---

proto/event/client/event.proto
proto/proto.lock

I'm adding `sdk_version` to the proto message so we can monitor the metrics by version instead of all SDKs.

chore: add sdk version property to proto metrics events

---

proto/event/client/event.proto
proto/proto.lock

I'm adding the metadata property to gather additional information from the client and server SDK to improve data analysis.
This will deliver to Kafka to ingest into Druid.
- [EvaluationEvent](https://github.com/bucketeer-io/bucketeer/blob/main/pkg/eventpersister/persister/persister.go#L336-L363)
- [GoalEvent](https://github.com/bucketeer-io/bucketeer/blob/main/pkg/eventpersister/persister/persister.go#L365-L412)

chore: add metadata property to proto client events

---

pkg/feature/api/tag.go
pkg/feature/api/tag_test.go

Currently, bucketeer server accepts tag consisting only of whitespace such as `"     "`. This PR fixes it.

chore: remove whitespaces from the tag before upserting it

---

pkg/gateway/api/api_grpc.go
proto/gateway/service.proto
proto/proto.lock

I'm adding JSON transcoding to track API for testing.
According to the google documentation, it will convert all query parameters automatically as defined in the `TrackRequest`.
Reference:
`
Any fields in the request message which are not bound by the path template automatically become HTTP query parameters if there is no HTTP request body.
`
https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#httprule

chore: add json transcoding to track api for testing

---

pkg/auditlog/api/api.go
pkg/autoops/api/api.go
pkg/autoops/api/webhook.go
pkg/environment/api/environment.go
pkg/environment/api/project.go
pkg/eventcounter/api/api.go
pkg/experiment/api/api.go
pkg/experiment/api/experiment.go
pkg/experiment/api/goal.go
pkg/feature/api/api.go
pkg/feature/api/feature.go
pkg/feature/api/feature_test.go
pkg/feature/api/segment.go
pkg/feature/api/segment_user.go
pkg/feature/api/tag.go
pkg/feature/api/user_evaluations.go
pkg/feature/api/validation.go
pkg/notification/api/admin_subscription.go
pkg/notification/api/api.go
pkg/notification/api/subscription.go
pkg/push/api/api.go
pkg/user/api/api.go
pkg/user/api/user.go

To support multiple languages in the error message, we have to stop using `localizedError`. This PR fixes one part of them.

refactor: do not use localizedError

---

pkg/gateway/api/api_grpc.go
pkg/gateway/api/api_grpc_test.go

I'm moving the `extractAPIKeyID` because the query parameter passes the API key in the Track API instead of the request header. 
So I'm refactoring the `getEnvironmentAPIKey` to work for both cases.

refactor: move extract api key calling to checkRequest func

---

.gitignore
proto/Makefile

- We use [gRPC-JSON transcoder](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter) on Envoy.
- gRPC-JSON transcoder needs descriptor files, which output by adding `--descriptor_set_out` to protoc command.
- Currently we are using the descriptor file output by bazel, but we will replace it.
- This change doesn't break bazel build.

build: generate proto_descriptor using protoc

---

pkg/experiment/cmd/batch/batch.go

Since there is no cost or performance issue, by executing it every 10 seconds, I'm changing it to improve the e2e test stability.

chore: change experiment updater cronjob settings

---

ui/web-v2/apps/admin/src/components/FeatureTargetingForm/index.tsx
ui/web-v2/apps/admin/src/pages/feature/targeting.tsx
ui/web-v2/apps/admin/src/utils/variation.ts

I'm adding the variation name in the input variation label to make it easier to understand which variation is, as a user suggested.
E.g.
```
variation_name - variation_value
```

chore: display variation name in the variation label

---

renovate.json

- renovate raises the PR [on the first day of the month](https://docs.renovatebot.com/presets-schedule/#schedulemonthly).
- renovate adds the label `renovate` to the PR.
- if updateType is minor, patch, pin or digest
- renovate adds the label `automerge by renovate` to the PR.
- renovate merges the PR automatically on Tuesday through Friday at 11 a.m. Japan time.
- FYI: [updateType](https://github.com/renovatebot/renovate/discussions/15360)
- renovate assigns the team [renovate-reviewers](https://github.com/orgs/bucketeer-io/teams/renovate-reviewers) to review the PR by human. 
- renovate doesn't assign a reviewer on the PR to be automerged.
- a reviewer is selected one person from the team with a round-robin strategy.

chore: configure renovate for automerge and assigning reviewers

---

manifests/bucketeer/charts/event-persister-user-events-kafka/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-user-events-kafka/values.yaml
manifests/bucketeer/values.yaml
pkg/eventpersister/cmd/server/server.go
pkg/eventpersister/persister/persister.go
pkg/eventpersister/persister/persister_test.go
pkg/eventpersister/storage/v2/mau.go
pkg/eventpersister/storage/v2/mau_test.go

- I updated the event persister to store MAU to MySQL.
- This app works without MySQL-related environment vars.
- `event-persister-evaluation-event` and `event-persister-goal-event` don't have to set the env vars.
- If storing to MySQL fails, storing to kafka is not executed.

chore: update eventpersister to store mau to mysql

---

manifests/bucketeer/charts/account-apikey-cacher/templates/envoy-configmap.yaml
manifests/bucketeer/charts/account/templates/envoy-configmap.yaml
manifests/bucketeer/charts/api-gateway/templates/envoy-configmap.yaml
manifests/bucketeer/charts/auditlog/templates/envoy-configmap.yaml
manifests/bucketeer/charts/auth/templates/envoy-configmap.yaml
manifests/bucketeer/charts/auto-ops/templates/envoy-configmap.yaml
manifests/bucketeer/charts/calculator/templates/envoy-configmap.yaml
manifests/bucketeer/charts/environment/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-counter/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-kafka/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-goal-events-kafka/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-user-events-kafka/templates/envoy-configmap.yaml
manifests/bucketeer/charts/experiment/templates/envoy-configmap.yaml
manifests/bucketeer/charts/feature-tag-cacher/templates/envoy-configmap.yaml
manifests/bucketeer/charts/feature/templates/envoy-configmap.yaml
manifests/bucketeer/charts/goal-batch-transformer/templates/envoy-configmap.yaml
manifests/bucketeer/charts/notification-sender/templates/envoy-configmap.yaml
manifests/bucketeer/charts/notification/templates/envoy-configmap.yaml
manifests/bucketeer/charts/ops-event-batch/templates/envoy-configmap.yaml
manifests/bucketeer/charts/push-sender/templates/envoy-configmap.yaml
manifests/bucketeer/charts/push/templates/envoy-configmap.yaml
manifests/bucketeer/charts/user-persister/templates/envoy-configmap.yaml
manifests/bucketeer/charts/user/templates/envoy-configmap.yaml

The health check in the egress settings is overwhelming the other services unnecessarily. All services have their own health check in the ingress settings.

chore: remove unnecessary health check in the envoy egress settings

---

manifests/bucketeer/charts/account-apikey-cacher/templates/envoy-configmap.yaml
manifests/bucketeer/charts/account/templates/envoy-configmap.yaml
manifests/bucketeer/charts/api-gateway/templates/envoy-configmap.yaml
manifests/bucketeer/charts/auditlog/templates/envoy-configmap.yaml
manifests/bucketeer/charts/auth/templates/envoy-configmap.yaml
manifests/bucketeer/charts/auto-ops/templates/envoy-configmap.yaml
manifests/bucketeer/charts/calculator/templates/envoy-configmap.yaml
manifests/bucketeer/charts/environment/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-counter/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-kafka/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-goal-events-kafka/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-user-events-kafka/templates/envoy-configmap.yaml
manifests/bucketeer/charts/experiment/templates/envoy-configmap.yaml
manifests/bucketeer/charts/feature-tag-cacher/templates/envoy-configmap.yaml
manifests/bucketeer/charts/feature/templates/envoy-configmap.yaml
manifests/bucketeer/charts/goal-batch-transformer/templates/envoy-configmap.yaml
manifests/bucketeer/charts/notification-sender/templates/envoy-configmap.yaml
manifests/bucketeer/charts/notification/templates/envoy-configmap.yaml
manifests/bucketeer/charts/ops-event-batch/templates/envoy-configmap.yaml
manifests/bucketeer/charts/push-sender/templates/envoy-configmap.yaml
manifests/bucketeer/charts/push/templates/envoy-configmap.yaml
manifests/bucketeer/charts/user-persister/templates/envoy-configmap.yaml
manifests/bucketeer/charts/user/templates/envoy-configmap.yaml

I'm removing unnecessary health checks that overwhelm other services when it deploys many pods.
For example, the api-gateway also checks for feature and account services, but they already check their health status.

chore: remove unnecessary health checks in the envoy settings

---

manifests/bucketeer/charts/event-persister-evaluation-events-kafka/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-kafka/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-kafka/values.yaml
manifests/bucketeer/charts/event-persister-goal-events-kafka/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-goal-events-kafka/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-goal-events-kafka/values.yaml
manifests/bucketeer/charts/event-persister-user-events-kafka/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-user-events-kafka/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-user-events-kafka/values.yaml

I'm adding these services as part of removing the Bigtable dependency.

chore: add event counter and experiment service's envoy config in the event persister

---

manifests/bucketeer/charts/api-gateway/templates/ingress.yaml

- I updated the ingress API version from `extensions/v1beta1` to `networking.k8s.io/v1`.
- related:
- https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-22#ingress-v122
- https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingress-v1-networking-k8s-io

chore: update ingress api version

---

pkg/eventpersister/persister/metrics.go
pkg/eventpersister/persister/persister.go
pkg/eventpersister/persister/persister_test.go
test/e2e/autoops/auto_ops_test.go
test/e2e/eventcounter/eventcounter_test.go

To solve the ordering of the events published from the api-gateway to Pubsub, I'm changing the event persister to link the goal event to the experiment before sending it to Kafka. 
To link the goal event, we need the evaluation event. If the goal event comes before the evaluation event, it will not acknowledge the Pubsub message until the evaluation event is sent to Kafka. If the evaluation event never came for some reason in the client after 24 hours, the persister will acknowledge the goal event, but it will not send to Kafka.
Also, I have changed the e2e tests to send the goal events before sending the evaluation events to ensure that implementation works.

chore: link the goal event to the experiment before sending it to kafka

---

manifests/bucketeer/charts/event-persister-evaluation-events-kafka/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-kafka/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-kafka/values.yaml
manifests/bucketeer/charts/event-persister-goal-events-kafka/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-goal-events-kafka/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-goal-events-kafka/values.yaml
manifests/bucketeer/charts/event-persister-user-events-kafka/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-user-events-kafka/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-user-events-kafka/values.yaml

Adding the auto ops service in the event persister as part of linking the goal event to auto ops rules.

chore: add auto ops service in the event persister envoy settings

---

pkg/cache/cache.go
pkg/cache/testing/cache.go
pkg/cache/v3/redis_cache.go
pkg/eventpersister/persister/persister.go
pkg/redis/v3/redis.go

Sample script to try this implementation
```go
func ExampleClient() {
rdb := goredis.NewClient(&goredis.Options{
Addr:     "localhost:6379",
Password: "", // no password set
DB:       0,  // use default DB
})
key := "key"
pipe := rdb.Pipeline()
d := pipe.TTL(ctx, key)
incr := pipe.Incr(ctx, key)
_, err := pipe.Exec(ctx)
if d.Val() == -1 {
rdb.Expire(ctx, key, time.Second*5)
}
fmt.Println(incr.Val(), err)
}
```

chore: add expiration to keys for evaluation counts

---

pkg/eventpersister/persister/persister.go
pkg/eventpersister/persister/persister_test.go

Due to performance issues, I'm removing the expiration setting when incrementing the event and user count.
I will add a cronjob to delete keys once daily instead of checking the TTL every time we increment the counter.
Also, I'm changing the key format so we can easily scan the keys by day when we delete them.
```
environment_namespace:kind:feature-id:variation-id:timestamp
↓
environment_namespace:kind:timestamp:feature-id:variation-id
```

chore: remove expiration setting from the event and user count

---

pkg/eventcounter/storage/v2/user_count.go

The service returns an error because SUM returns NULL when there is no value.

fix: internal error when there is no value in the event count

---

.github/workflows/push-image.yaml

Like the `publish-chart` workflow, the `push-image` workflow must wait for the release workflow until it finishes. Otherwise, it could get the wrong version.

ci: fix the publish image version that is incorrect when the tag is created

---

pkg/eventpersister/persister/metrics.go
pkg/eventpersister/persister/persister.go
pkg/eventpersister/persister/persister_test.go

Because the calculator service already adds a buffer of 48 hours before stopping the running experiments, there is no need to validate the timestamp. Also, there is no need to list stopped experiments.
- Changed to list only running experiments
- Removed timestamp validation

fix: goal event not being acknowledged correctly

---

pkg/eventpersisterdwh/persister/evaluation_event.go
pkg/eventpersisterdwh/persister/goal_event.go
pkg/eventpersisterdwh/persister/persister_test.go

Here is a screen shot to prove this implementation works.

fix: insert timestamp correctly in bigquery

---

pkg/eventcounter/storage/v2/sql/evaluation_count.sql
pkg/eventcounter/storage/v2/sql/goal_count.sql

- We chose the time-unit column partitioning instead of the ingestion time partitioning.
- https://cloud.google.com/bigquery/docs/partitioned-tables
- A pseudo column named `_PARTITIONTIME` doesn't exist when you use the time-unit column partitioning.

chore: update BigQuery query files

---

cmd/eventpersisterops/eventpersisterops.go
manifests/bucketeer/charts/event-persister-evaluation-events-ops/.helmignore
manifests/bucketeer/charts/event-persister-evaluation-events-ops/Chart.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-ops/templates/_helpers.tpl
manifests/bucketeer/charts/event-persister-evaluation-events-ops/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-ops/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-ops/templates/hpa.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-ops/templates/service-account.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-ops/templates/service-cert-secret.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-ops/templates/service-token-secret.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-ops/templates/service.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-ops/values.yaml
manifests/bucketeer/charts/event-persister-goal-events-ops/.helmignore
manifests/bucketeer/charts/event-persister-goal-events-ops/Chart.yaml
manifests/bucketeer/charts/event-persister-goal-events-ops/templates/_helpers.tpl
manifests/bucketeer/charts/event-persister-goal-events-ops/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-goal-events-ops/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-goal-events-ops/templates/hpa.yaml
manifests/bucketeer/charts/event-persister-goal-events-ops/templates/service-account.yaml
manifests/bucketeer/charts/event-persister-goal-events-ops/templates/service-cert-secret.yaml
manifests/bucketeer/charts/event-persister-goal-events-ops/templates/service-token-secret.yaml
manifests/bucketeer/charts/event-persister-goal-events-ops/templates/service.yaml
manifests/bucketeer/charts/event-persister-goal-events-ops/values.yaml
manifests/bucketeer/values.yaml
pkg/eventpersisterops/cmd/server/eventpersisterops.go
pkg/eventpersisterops/persister/persister.go
tools/build/show-image-name.sh

To keep the PR small, I'm adding the persister implementation in another PR.
- Add the helm manifest
- Add event persister ops to the container images list
- Add the persister service (health check only)

chore: add cmd for event persister ops

---

pkg/cache/v3/eventcounter.go
pkg/cache/v3/mock/eventcounter.go
pkg/eventpersisterops/cmd/server/eventpersisterops.go
pkg/eventpersisterops/persister/evaluation_event.go
pkg/eventpersisterops/persister/event.go
pkg/eventpersisterops/persister/goal_event.go
pkg/eventpersisterops/persister/metrics.go
pkg/eventpersisterops/persister/persister.go
pkg/opsevent/batch/job/count_watcher.go
pkg/opsevent/batch/job/count_watcher_test.go

As part of BigQuery migration, I'm changing the Auto Ops to write/read the ops event count from Redis to reduce costs.
I will write the unit tests in another PR, but I have already tested it on the dev environment, and the e2e tests have passed.
- Added event persister service for auto ops
- Change the ops event count watcher to get the ops event count from Redis

chore: add event persister service for auto ops

---

pkg/autoops/api/api.go
pkg/autoops/api/api_test.go
pkg/autoops/api/operation.go

If the user schedule to turn on a flag, and before the auto ops run, he enables the flag, it will treat it as an error, so I'm changing the ExecuteOperation to return nil if the operation is already done.
- Changed to check if the ops have been triggered outside of the transaction
- Changed not to treat as an error if no rows were affected
- Split the logs in the operation to make debugging easier

fix: mysql error alerts when the auto ops rule is already triggered

---

pkg/eventcounter/api/api.go
pkg/eventcounter/api/api_test.go
pkg/eventpersisterops/persister/evaluation_event.go
pkg/eventpersisterops/persister/goal_event.go

I'm changing the auto ops key format so that we can easily scan the keys by feature id.

chore: change auto ops count key format

---

docs/rfcs/0002-improve-evaluation-count.md

I'm writing this proposal to solve the following issues.
- The data retrieval is done in milliseconds instead of 5-20 seconds
- Split the data pipeline for Feature Flag and A/B Test, making the self-host process simple and cheaper
- Be able to see the default value count

docs: add rfc for evaluation count improvements

---

docs/rfcs/0003-improve-mau-count-speed.md

We'll migrate the user event data from Druid to another DB to achieve the following goal.
- Retrieve the MAU count faster. Currently, it takes more than 1 hour depending on the number of events stored in the Druid, and sometimes it fails during the querying

docs: add rfc for mau count retrieval improvements

---

pkg/gateway/api/api_grpc.go
pkg/gateway/api/api_grpc_test.go
pkg/gateway/api/metrics.go
pkg/gateway/api/metrics_event.go
pkg/gateway/api/metrics_event_test.go
pkg/gateway/cmd/server.go
test/e2e/gateway/api_grpc_test.go

- move function saving metrics event to the api-gateway
- add new metrics event according to HTTP status code
- add e2e test for metrics event saving

chore: move function saving metrics event to gateway

---

manifests/bucketeer/charts/event-persister-evaluation-events-dwh/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/values.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/values.yaml
pkg/eventpersisterdwh/cmd/server/eventpersisterdwh.go
pkg/eventpersisterdwh/persister/evaluation_event.go
pkg/eventpersisterdwh/persister/goal_event.go
pkg/eventpersisterdwh/persister/metrics.go
pkg/eventpersisterdwh/persister/persister.go
pkg/eventpersisterdwh/persister/persister_test.go
test/e2e/eventcounter/eventcounter_test.go

Instead of using Bigtable to save the user evaluations, I changed it to evaluate the user to get the needed data to save the goal event.
Doing this, will simplify the data pipeline when supporting a multi-cloud platform and reduce costs.
I will remove the Bigtable client in another PR.

chore: remove bigtable from event persister DWH

---

python/requirements.txt

Reverts bucketeer-io/bucketeer#222
numpy 1.22 requires python >= 3.8.

revert: update dependency numpy to v1.22.0 [security]

---

.github/workflows/pr-python.yaml

I addressed to a [PR](https://github.com/bucketeer-io/bucketeer/pull/222/checks) that passed test but did not pass build.

ci: add build step to workflow for validating pull request for python

---

pkg/storage/v2/mysql/client.go

- SetConnMaxLifetime
- https://pkg.go.dev/database/sql#DB.SetConnMaxLifetime
- SetConnMaxIdleTime
- https://pkg.go.dev/database/sql#DB.SetConnMaxIdleTime

chore: set mysql client's connection max idle time instead of lifetime

---

manifests/bucketeer/charts/web-gateway/templates/backend-config.yaml

- To handle requests to get MAU, which takes over 40 seconds.

chore: modify timeout second of web-gateway backend

---

pkg/gateway/api/api_grpc.go
pkg/gateway/api/api_grpc_test.go

- This PR adds functions to get the prerequisites of features recursively.
- `getPrerequisiteDownwards` gets the features specified as prerequisite by the targetFeatures.
- `getPrerequisiteUpwards gets the features that have the specified targetFeatures as the prerequisite.
- This PR modifies the behavior of GetEvaluation to evaluation only features with prerequisites instead of all features.

chore: add function to get prerequisites

---

pkg/gateway/api/api.go
pkg/gateway/api/api_grpc.go

- This PR removes the user metadata from the user event.
- We don't use the metadata now, so removes it until we decide again what to do with.

chore: remove user metadata from user event

---

pkg/feature/api/feature.go
pkg/feature/domain/feature.go
pkg/gateway/api/api.go
pkg/gateway/api/api_grpc.go
pkg/gateway/api/api_grpc_test.go
pkg/gateway/api/api_test.go
pkg/notification/sender/informer/batch/job/feature_watcher.go
pkg/push/sender/sender.go
pkg/push/sender/sender_test.go

- This PR changes the caching behavior to add archived feature flags to the Redis.
- To keep the cache size small, feature flags archived more than thirty days ago are excluded.
- To follow the existing behavior of the api-gateway, I added a function to filter out archived features before the response. (This function was temporarily added. I will remove it when I implement a differential evaluation feature.)

chore: add archived feature flags to the cache

---

pkg/feature/domain/evaluation.go
pkg/feature/domain/evaluation_test.go
pkg/gateway/api/api_grpc.go

- Adds tag filtering to the evaluation by `evaluatedAt`.
- Renames variable `isUserAttributesUpdated` to `userAttributesUpdated`

chore: add tag filtering to evaluation by evaluatedAt

---

.github/dependabot.yaml

We plan to remove python implementation in the feature. Thus, we don't need to update python dependencies.

chore: stop updating pip dependency group

---

.github/workflows/auto_merge.yaml

API rate limit error such as https://github.com/bucketeer-io/bucketeer/actions/runs/5129569875/jobs/9227333942#step:2:287 occurs when CI for Dependabot runs.
Thus, the waiting interval should be longer. This PR fixes it.

chore: change the wait-interval field in lewagon/wait-on-check-action

---

tools/httpstan/Dockerfile
tools/httpstan/Makefile
tools/httpstan/README.md
tools/httpstan/httpstan_api_test.py

This pull request is part of imlementation of this [issue](https://github.com/bucketeer-io/bucketeer/issues/356), used to create the Docker image for the [HttpStan](https://github.com/stan-dev/httpstan) 
This commit adds four new files to the tools/httpstan directory: `Dockerfile`, `Makefile`, `README.md`, and `httpstan_api_test.py` 
* The `Dockerfile` is used to build the HttpStan Docker image
* The `Makefile` includes targets for building and pushing the Docker image
* The `httpstan_api_test.py` script contains a function that tests the `POST /v1/models` endpoint, which is used to compile a model. As you can see, the stan script that used to test HttpStan compile API is the script that Python Calculator was using
* The `README.md` explains how to build and run the HttpStan Docker image …

feat: build httpstan image

---

manifests/bucketeer/charts/api-gateway/templates/service-account.yaml
manifests/bucketeer/charts/auditlog-persister/templates/service-account.yaml
manifests/bucketeer/charts/auditlog/templates/service-account.yaml
manifests/bucketeer/charts/auth/templates/service-account.yaml
manifests/bucketeer/charts/auto-ops/templates/service-account.yaml
manifests/bucketeer/charts/calculator/templates/service-account.yaml
manifests/bucketeer/charts/dex/templates/service-account.yaml
manifests/bucketeer/charts/environment/templates/service-account.yaml
manifests/bucketeer/charts/event-counter/templates/service-account.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/templates/service-account.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-evaluation-count/templates/service-account.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-ops/templates/service-account.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/templates/service-account.yaml
manifests/bucketeer/charts/event-persister-goal-events-ops/templates/service-account.yaml
manifests/bucketeer/charts/experiment/templates/service-account.yaml
manifests/bucketeer/charts/feature-recorder/templates/service-account.yaml
manifests/bucketeer/charts/feature-segment-persister/templates/service-account.yaml
manifests/bucketeer/charts/feature/templates/service-account.yaml
manifests/bucketeer/charts/metrics-event-persister/templates/service-account.yaml
manifests/bucketeer/charts/migration-mysql/templates/service-account.yaml
manifests/bucketeer/charts/notification-sender/templates/service-account.yaml
manifests/bucketeer/charts/notification/templates/service-account.yaml
manifests/bucketeer/charts/ops-event-batch/templates/service-account.yaml
manifests/bucketeer/charts/push-sender/templates/service-account.yaml
manifests/bucketeer/charts/push/templates/service-account.yaml
manifests/bucketeer/charts/user-persister/templates/service-account.yaml
manifests/bucketeer/charts/web-gateway/templates/service-account.yaml
manifests/bucketeer/charts/web/templates/service-account.yaml

- This PR changes the service-account name because they have conflicts. 
- e.g., There is a name conflict between `event-persister-evaluation-events-dwh` and `event-persister-goal-events-dwh`.

chore: change service-accounts name

---

pkg/gateway/api/api_grpc.go
pkg/gateway/api/api_grpc_test.go
pkg/gateway/api/metrics.go

Currently, buckteer generates the UserEvaluationsID from all active(not archived) features.
This method results in unnecessary evaluations when features with other tags are updated.
e.g., Even when only the feature with the `ios` tag is updated, the features with other tags such as `web` or `android` will be evaluated.
- This PR modifies the method of generating the UEID to generate them from the features filtered by the specified tag.

perf: generate the UEID from the features filtered by the tag

---

manifests/bucketeer/charts/account-apikey-cacher/templates/envoy-configmap.yaml
manifests/bucketeer/charts/api-gateway/templates/envoy-configmap.yaml
manifests/bucketeer/charts/auditlog/templates/envoy-configmap.yaml
manifests/bucketeer/charts/auto-ops/templates/envoy-configmap.yaml
manifests/bucketeer/charts/backend/templates/envoy-configmap.yaml
manifests/bucketeer/charts/environment/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-counter/templates/envoy-configmap.yaml
manifests/bucketeer/charts/experiment/templates/envoy-configmap.yaml
manifests/bucketeer/charts/feature/templates/envoy-configmap.yaml
manifests/bucketeer/charts/notification/templates/envoy-configmap.yaml
manifests/bucketeer/charts/push/templates/envoy-configmap.yaml
manifests/bucketeer/charts/web-gateway/templates/envoy-configmap.yaml

- This PR adds routing settings to the backend service from other microservices.
- After this PR is merged, requests will no longer be sent to the `auth` and `account` services.

chore: add routing from other microservices to backend service

---

pkg/eventcounter/api/api.go

chore: include the current hour in GetEvaluationTimeseriesCount

---

manifests/bucketeer/charts/account-apikey-cacher/templates/envoy-configmap.yaml
manifests/bucketeer/charts/backend/templates/deployment.yaml
manifests/bucketeer/charts/backend/templates/envoy-configmap.yaml
manifests/bucketeer/charts/backend/values.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-ops/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-goal-events-ops/templates/envoy-configmap.yaml
manifests/bucketeer/charts/notification-sender/templates/envoy-configmap.yaml
manifests/bucketeer/charts/ops-event-batch/templates/envoy-configmap.yaml
manifests/bucketeer/charts/web-gateway/templates/envoy-configmap.yaml
pkg/backend/cmd/server/server.go

- This PR integrates the audit-log, the auto-ops, and the environment service into the backend module.
- This PR adds routing settings to the backend service from other microservices.
- After this PR is merged, requests will no longer be sent to the audit-log, auto-ops, and environment services.

chore: add audit-log, auto-ops, environment service into the backend module

---

Makefile

Currently, generated proto files are checked in CI. If we update proto files, we must run all proto commands in each directory. Thus, it would be useful if we update all generated proto files in one command. I introduced proto-all command in this PR.

chore: add proto-all command in Makefile

---

manifests/bucketeer/charts/event-persister-evaluation-events-dwh/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-ops/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/templates/envoy-configmap.yaml
manifests/bucketeer/charts/event-persister-goal-events-ops/templates/envoy-configmap.yaml
manifests/bucketeer/charts/notification-sender/templates/envoy-configmap.yaml
manifests/bucketeer/charts/ops-event-batch/templates/envoy-configmap.yaml
manifests/bucketeer/charts/push-sender/templates/envoy-configmap.yaml
manifests/bucketeer/charts/push/templates/envoy-configmap.yaml
manifests/bucketeer/charts/web-gateway/templates/envoy-configmap.yaml

- This PR adds the route to the event-counter, experiment, and feature services in the backend module.
- Once this PR is merged, requests to the event-counter, experiment, and feature module will no longer be sent.

chore: add routing to event-counter, experiment, feature in the backend module

---

manifests/bucketeer/charts/backend/templates/deployment.yaml
manifests/bucketeer/charts/backend/templates/envoy-configmap.yaml
manifests/bucketeer/charts/backend/values.yaml
pkg/backend/cmd/server/server.go

- This PR integrates the migration-mysql, notification and push service into the backend module.
- Even if this PR is merged, requests will be sent to the migration-mysql, notification and push services from the web-gateway.

chore: add migration-mysql, notification, push  service into the backend  module

---

manifests/bucketeer/charts/api-gateway/templates/envoy-configmap.yaml
manifests/bucketeer/charts/calculator/templates/envoy-configmap.yaml
manifests/bucketeer/charts/notification-sender/templates/envoy-configmap.yaml
manifests/bucketeer/charts/push-sender/templates/envoy-configmap.yaml
manifests/bucketeer/charts/web-gateway/templates/envoy-configmap.yaml

- This PR adds the route to the migration-mysql, notification, and push services in the backend module.
- Once this PR is merged, requests to the migration-mysql, notification, and push module will no longer be sent.

chore: add routing to migration-mysql, notification, push in the backend module

---

Makefile

- We must uninstall `github.com/golang/mock/mockgen@v1.6.0` and install `go.uber.org/mock/mockgen@0.1.0` before running the command `make mockgen` since [this PR](https://github.com/bucketeer-io/bucketeer/pull/435) was merged.

chore: fix mockgen version

---

tools/httpstan/Dockerfile
tools/httpstan/httpstan_api_test.py
tools/httpstan/model.stan
tools/httpstan/stan_model_compile.py

Golang calculator service(https://github.com/bucketeer-io/bucketeer/pull/395) need to call httpstan to compile the stan model code first. And it could take long time to finish compile progress.
So this PR will precompile the stan model that we use in Golang calculator service and save the precompiled model files in the HttpStan Docker image directly. Then we can skip compile model in the Golang calculator service pod to speed up service start.
* Implement a precompile model python script, the script will start a httpstan server "locally" then call the httpstan's compile model http endpoint.
* After httpstan finished to compile model, it will save the compiled model in the following directory:
`/root/.cache/httpstan/${httpstan_version}/models/${model_id}`.
NOTE: the `model_id` was …

chore: precompile stan model

---

pkg/account/apikeycacher/apikeycacher.go

- This PR fixes the bug that makes `not found` error during the apikey cacher running.

fix: environment is not found error during operation of apikey-cacher

---

manifests/bucketeer/charts/event-persister-evaluation-events-dwh/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/values.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/values.yaml
pkg/eventpersisterdwh/cmd/server/eventpersisterdwh.go
pkg/eventpersisterdwh/persister/evaluation_event.go
pkg/eventpersisterdwh/persister/goal_event.go
pkg/eventpersisterdwh/persister/persister.go
pkg/eventpersisterdwh/persister/persister_test.go

Because the evaluation and goal events may be sent with a delay for many reasons from the client side,
We should still calculate the results after the experiment stops.
E2E tests have passed.

chore: change list experiments condition in the event persister

---

pkg/account/cmd/apikeycacher/apikeycacher.go
pkg/auditlog/cmd/persister/persister.go
pkg/eventpersister/cmd/server/server.go
pkg/eventpersisterdwh/cmd/server/eventpersisterdwh.go
pkg/eventpersisterops/cmd/server/eventpersisterops.go
pkg/experimentcalculator/cmd/server/server.go
pkg/feature/cmd/recorder/recorder.go
pkg/feature/cmd/segmentpersister/persister.go
pkg/gateway/cmd/server.go
pkg/health/health.go
pkg/metricsevent/cmd/persister/persister.go
pkg/notification/cmd/sender/sender.go
pkg/opsevent/cmd/batch/batch.go
pkg/push/cmd/sender/sender.go
pkg/user/cmd/persister/persister.go

Ensure to stop the health check before stopping the application so the Kubernetes Readiness can detect it faster and remove the pod from the service load balancer.

chore: add stop function to be called when the app gets the sigterm signal

---

.github/workflows/pr-ui-web.yaml
.github/workflows/push-image.yaml

- removes needless proto-compile processes.
- modifies go build process so that it works concurrently.
- [Concurrent go build process took 1m4s](https://github.com/bucketeer-io/bucketeer/actions/runs/5620512977/job/15229596827). (Sequential build process takes about 2min.)

ci: compress build time 

---

pkg/cache/v3/features.go
pkg/cache/v3/segment_users.go

- This PR sets to 0 the TTL of the features and user-segments caches.
- We discussed the risk of MySQL's downtime and decided to change the TTL setting so that not to clear the cache.
- As for refreshing the cache, we plan to do it more securely.

chore: adjust features and segments cache TTL

---

pkg/environment/api/environment.go
pkg/environment/api/environment_test.go
pkg/environment/api/environment_v2.go
pkg/environment/api/project.go
pkg/environment/domain/environment.go

- Temporarily, the environment API V1 persists objects to V1 and V2 tables until all V1 API will be replaced.

chore: modify environment APIs to write v1 and v2 temporarily

---

manifests/bucketeer/charts/backend/templates/deployment.yaml
pkg/backend/cmd/server/server.go

- We need stronger permission to migrate the DB structure than usual manipulation such as SELECT, CREATE, and so on.
- So, I separate the MySQL user and pass configs.

feat: separete the mysql config for DDL and DML

---

Makefile
manifests/bucketeer/charts/batch/Chart.yaml
manifests/bucketeer/charts/batch/templates/NOTES.txt
manifests/bucketeer/charts/batch/templates/_helpers.tpl
manifests/bucketeer/charts/batch/templates/cronjob.yaml
manifests/bucketeer/charts/batch/templates/deployment.yaml
manifests/bucketeer/charts/batch/templates/envoy-configmap.yaml
manifests/bucketeer/charts/batch/templates/pdb.yaml
manifests/bucketeer/charts/batch/templates/service-account.yaml
manifests/bucketeer/charts/batch/templates/service-cert-secret.yaml
manifests/bucketeer/charts/batch/templates/service-token-secret.yaml
manifests/bucketeer/charts/batch/templates/service.yaml
manifests/bucketeer/charts/batch/values.yaml

* This PR will create the new batch service helm charts
* Aside the batch service deployment, there is also contain the cronjob of batch service API call
Currently we have Envoy gRPCJsonTranscoder, so I am using `Curl` Docker image to make requests against the `web-gateway`.
The batch job gRPC service [proto file](https://github.com/bucketeer-io/bucketeer/pull/450/files#diff-4a0ee597c9cb3813733ef8488a35bb75aa660c13f9a251b08f2412f9a6c4c741). 
The cronjob in `pkg/opsevent/cmd/batch/batch.go` was executed every 10 second. 
Reference: https://github.com/bucketeer-io/bucketeer/issues/428#issuecomment-1614321392
But the cronjob in kubernetes can't schedule job in second level, so currently we are executing these jobs every minute.
Reference: …

chore: batch service helm charts

---

pkg/batch/api/api_test.go
pkg/batch/jobs/experiment/experiment_status_updater.go
pkg/batch/jobs/notification/domain_event_informer.go
pkg/batch/jobs/notification/experiment_running_watcher.go
pkg/batch/jobs/notification/experiment_running_watcher_test.go
pkg/batch/jobs/notification/feature_stale_watcher.go
pkg/batch/jobs/notification/feature_stale_watcher_test.go
pkg/batch/jobs/notification/mau_count_watcher.go
pkg/batch/jobs/notification/mau_count_watcher_test.go
pkg/experimentcalculator/experimentcalc/experiment_calculator.go

- This PR replaces v1 environment API (GetEnvironmentByNamespace, ListEnvironments) in the batch and calculator to v2.

chore: migrate v1 environment api to v2 in batch and calculator

---

pkg/batch/cmd/server/server.go
pkg/environment/api/environment_v2.go
pkg/environment/api/environment_v2_test.go

- This PR modifies the GetEnvironmentV2 API to retrieve the environment even with an empty ID.
- This PR fixes the batch server doesn't emit logs.

fix: getEnvironmentV2 fails to get env with empty ID

---

pkg/batch/jobs/notification/mau_count_watcher_test.go

I noticed an error while executing the Github Action `pr-go`. This [line](https://github.com/bucketeer-io/bucketeer/blob/main/pkg/batch/jobs/notification/mau_count_watcher_test.go#L175)  has not been set to the same timzone as the [line](https://github.com/bucketeer-io/bucketeer/blob/main/pkg/batch/jobs/notification/mau_count_watcher.go#L75) in `mauCountWatcher.Run` function. 
Due to the timezone used in `mauCountWatcher` being `Japan`, when I ran this unit test in the `Beijing` timezone on August 31, 2023, at 11:56 PM, I encountered the following error:
So, we should set the same time zone in the unit test. :)

fix: time location in unit test

---

test/e2e/environment/environment_test.go

- Remove the update environment v1 test because it interferes with the v2 test and causes it to fail.

chore: remove update env v1 test

---

pkg/eventpersisterdwh/persister/evaluation_event.go
pkg/eventpersisterdwh/persister/goal_event.go
pkg/eventpersisterdwh/persister/persister_test.go

Because the user data is optional, when the data is nil, it saves as a `null` string in the BigQuery, which could cause issues when querying.

chore: set empty map when the user data is nil

---

pkg/feature/api/error.go
pkg/feature/api/feature_test.go
pkg/feature/api/validation.go
test/e2e/feature/feature_test.go

We need to remove the tag validation because the tag is now optional. Otherwise, linking the experiment to a flag could not work if the tag is empty.

chore: remove the tag validation for evaluate feature api

---

pkg/eventpersisterdwh/persister/evaluation_event.go
pkg/eventpersisterdwh/persister/goal_event.go
pkg/eventpersisterdwh/persister/metrics.go
pkg/eventpersisterdwh/persister/persister.go
pkg/eventpersisterdwh/persister/persister_test.go

To avoid saving events that won't be calculated by the experiment calculator, I changed the condition to ignore events older than the experiment's `stopAt`.

chore: change not to save events after the experiment is ended

---

manifests/bucketeer/charts/account-apikey-cacher/templates/hpa.yaml
manifests/bucketeer/charts/api-gateway/templates/hpa.yaml
manifests/bucketeer/charts/api-gateway/templates/pdb.yaml
manifests/bucketeer/charts/auditlog-persister/templates/hpa.yaml
manifests/bucketeer/charts/backend/templates/hpa.yaml
manifests/bucketeer/charts/backend/templates/pdb.yaml
manifests/bucketeer/charts/batch/templates/pdb.yaml
manifests/bucketeer/charts/dex/templates/pdb.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-dwh/templates/hpa.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-evaluation-count/templates/hpa.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-ops/templates/hpa.yaml
manifests/bucketeer/charts/event-persister-goal-events-dwh/templates/hpa.yaml
manifests/bucketeer/charts/event-persister-goal-events-ops/templates/hpa.yaml
manifests/bucketeer/charts/experiment-calculator/templates/hpa.yaml
manifests/bucketeer/charts/experiment-calculator/templates/pdb.yaml
manifests/bucketeer/charts/feature-segment-persister/templates/hpa.yaml
manifests/bucketeer/charts/metrics-event-persister/templates/hpa.yaml
manifests/bucketeer/charts/user-persister/templates/hpa.yaml
manifests/bucketeer/charts/web-gateway/templates/hpa.yaml
manifests/bucketeer/charts/web-gateway/templates/pdb.yaml
manifests/bucketeer/charts/web/templates/hpa.yaml
manifests/bucketeer/charts/web/templates/pdb.yaml

- `autoscaling/v2beta1` and `policy/v1beta1` API are deleted on the Kubernetes1.25.

chore: update the deprecated kubernetes api

---

hack/create-project/README.md
hack/create-project/command.go

There is a bug while creating the environment. Instead of passing the project ID, it passes a random uuid as the project ID.
- Fixed the project ID
- Changed the flag from `bool` to `strings` so the user can pass the environment he wants instead of always creating 3 environments as default.
- Added the flag `url-code` instead of using the name
- Updated the README

fix: project hack script not creating environment correctly

---

pkg/account/cmd/apikeycacher/apikeycacher.go
pkg/backend/cmd/server/server.go
pkg/batch/cmd/server/server.go
pkg/eventpersister/cmd/server/server.go
pkg/eventpersisterops/cmd/server/eventpersisterops.go
pkg/feature/cmd/segmentpersister/persister.go
pkg/gateway/cmd/server.go
pkg/push/cmd/sender/sender.go

We already have an interface to check the Redis status, but we didn't implement it in the container health check.
By implementing this If for some reason the container gets a Redis connection failure, it will restart the container to recreate the connection.

chore: add redis connection status to health check

---

pkg/eventpersisterdwh/persister/evaluation_event.go
pkg/eventpersisterdwh/persister/goal_event.go
pkg/eventpersisterdwh/persister/metrics.go
pkg/eventpersisterdwh/persister/persister.go
pkg/eventpersisterdwh/persister/persister_test.go
pkg/eventpersisterops/persister/evaluation_event.go
pkg/eventpersisterops/persister/goal_event.go
pkg/eventpersisterops/persister/metrics.go
pkg/eventpersisterops/persister/persister.go

Instead of requesting the same data for each event, I changed it to request just once per batch. This will improve the load on Redis.

perf: improve redis load in the event persisters

---

.github/workflows/code-butler.yaml

By specifying gpt-4-1106-preview as the model for code-butler, PRs with many differences can be reviewed at once.
However, since OpenAI's paid plan Token is required, you need to update your Token before Merge this PR.

build: specify gpt-4-1106-preview as the model for code-butler

---

hack/delete-e2e-data-mysql/command.go
test/e2e/feature/feature_flag_trigger_test.go

Fixes the following error when deleting the e2e data.
``
{"severity":"ERROR","eventTime":1703534508.67749,"logger":"delete.delete","caller":"delete-e2e-data-mysql/command.go:92","message":"Failed to delete data","serviceContext":{"service":"delete.delete","version":"-"},"error":"Error 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`master`.`flag_trigger`, CONSTRAINT `foreign_flag_trigger_feature_id_environment_namespace` FOREIGN KEY (`feature_id`, `environment_namespace`) REFERENCES `feature` (`id`, `environment_namespa)","table":"feature","stacktrace":"main.
``

fix: cannot delete or update a parent row when deleting e2e data

---

pkg/autoops/api/progressive_rollout.go

It returns an error even if the operation is completed.

fix: validation while creating a progressive rollout

---

pkg/account/api/account.go
pkg/account/api/account_test.go
pkg/account/api/error.go
pkg/account/domain/account.go
pkg/account/domain/account_test.go

- adds implementation for double write accounts v1 and v2.
- This implementation is needed so that the users can create/update/delete account v2 at the same time as account v1.

chore: add double write account v1 and v2

---

test/e2e/feature/feature_flag_trigger_test.go

The delete e2e data workflow fails when deleting the feature flags because we must delete the trigger first.
There was one place that didn't set the test id in the description.

test: fix delete e2e data not working

---

pkg/account/api/account.go
pkg/account/api/api.go
pkg/account/api/api_key.go
pkg/auditlog/api/api.go
pkg/auditlog/api/api_test.go
pkg/autoops/api/api.go
pkg/autoops/api/api_test.go
pkg/autoops/api/progressive_rollout.go
pkg/autoops/api/progressive_rollout_test.go
pkg/autoops/api/webhook.go
pkg/eventcounter/api/api.go
pkg/eventcounter/api/api_test.go
pkg/experiment/api/api.go
pkg/experiment/api/api_test.go
pkg/experiment/api/experiment.go
pkg/experiment/api/goal.go
pkg/feature/api/api.go
pkg/feature/api/api_test.go
pkg/feature/api/feature.go
pkg/feature/api/flag_trigger.go
pkg/feature/api/segment.go
pkg/feature/api/segment_user.go
pkg/feature/api/tag.go
pkg/notification/api/api.go
pkg/notification/api/subscription.go
pkg/push/api/api.go
pkg/role/role.go
pkg/role/role_test.go

This PR updates the `CheckRole()` function in the `/pkg/role/role.go` to use the accountV2 instead of the accountV1.
The following modules use the `CheckRole()`, so they are modified.

chore: replace account v1 to v2 when checking the role

---

pkg/gateway/api/api_grpc.go

Related fixes for #662.
It is correct to pass "UrlCode" instead of Environment's "ID".

fix: change the api-gateway metrics label

---

.github/workflows/push-image.yaml

Checked locally 👍 
```sh
> act -j setup -e event.json
...
[push-image/setup]   ✅  Success - Main Store the first line of commit message
[push-image/setup]   ⚙  ::set-output:: value=Update README.md
```

ci: fix setup job fails in workflow

---

.github/.devcontainer/Dockerfile
.github/.devcontainer/devcontainer-lock.json
.github/.devcontainer/devcontainer.json
.github/.devcontainer/first-run-notice.txt
.github/.devcontainer/local-features/setup-user/devcontainer-feature.json
.github/.devcontainer/local-features/setup-user/install.sh
.github/workflows/devcontainer-image-build.yaml

Fixes https://github.com/bucketeer-io/bucketeer/issues/134
- This PR will add a Github Workflow file that builds the base image used by the Dev Container.
- This Workflow is designed to be run manually. Whenever we update the Bucketeer project dependency or tools, we can trigger the build workflow as needed.
The dev container image name will be: `ghcr.io/bucketeer-io/bucketeer-devcontainer`

chore: build dev container base image

---

.github/workflows/push-image.yaml

Fixes https://github.com/bucketeer-io/bucketeer/issues/717
We didn't have the directory `.devcontainer` when this workflow was created. When we made changes to the `.devcontainer`, it triggered only the `push-image` workflow, causing errors on the PipeCD because the helm chart doesn't exist, which is expected. So, I'm fixing the condition to match the `push_chart` workflow.

ci: fix push-image triggering when pushing ci code

---

pkg/account/api/admin_account.go
pkg/account/api/admin_account_test.go
pkg/account/storage/v2/admin_account.go
pkg/account/storage/v2/admin_account_test.go
pkg/account/storage/v2/mock/storage.go
pkg/account/storage/v2/sql/account_v2/select_admin_account_v2.sql
pkg/account/storage/v2/storage.go

- The old getAdminAccount() function retrieves objects from the `admin_account` table.
- The new getAdminAccountV2() function retrieves the account belonging to the System Admin Organization.

chore: update the process getting AdminAccount

---

hack/delete-e2e-data-mysql/command.go

- We've already deleted the webhook table.

chore: remove webhook table from delete-e2e targets

---

hack/generate-service-token/command.go
pkg/token/idtoken.go

part of https://github.com/ca-dp/bucketeer-issue/issues/5
This pull request primarily focuses on refactoring the token generation process in the `hack/generate-service-token/command.go` file and updating the `IDToken` struct in the `pkg/token/idtoken.go` file. The key changes include replacing the `ioutil.WriteFile` function with `os.WriteFile`, adding an `IsSystemAdmin` field to the `IDToken` struct, and updating the token generation process to set `IsSystemAdmin` to `true`.
Here are the main changes:
* `hack/generate-service-token/command.go`: 
* Replaced the `ioutil.WriteFile` function with `os.WriteFile` to write the signed ID token to a file. This change is in line with the deprecation of `ioutil` in Go 1.16. [[1]](diffhunk://#diff-cb32802d4e8e7750abbbc9e43742a3694197cb014d853d99a1724 …

chore: add system admin flag to idtoken

---

pkg/account/api/admin_account.go
pkg/account/api/admin_account_test.go
pkg/account/storage/v2/admin_account.go
pkg/account/storage/v2/admin_account_test.go
pkg/account/storage/v2/mock/storage.go
pkg/account/storage/v2/storage.go

Now we have two admins;
- system admin
- organizational admin
They should be explicitly used correctly to avoid confusion.

refactor: use system admin word correctly

---

pkg/account/storage/v2/account_test.go
pkg/account/storage/v2/storage.go

We don't need `tx` field in `accountStorage`, we can remove it.
```go
type accountStorage struct {
client mysql.Client
tx     mysql.Transaction
}
```

chore: remove tx field in accountStorage

---

pkg/feature/api/api.go
pkg/feature/api/api_test.go
pkg/feature/api/flag_trigger.go
pkg/feature/api/flag_trigger_test.go

This pull request primarily includes adding unit tests for FlagTrigger and changes to the Bucketeer project's "pkg/feature/api" package. This change focuses on refactoring the `FeatureService` structure and related methods in `api.go` and `flag_trigger.go` to use the new `v2fs` package for feature storage. Additionally, error handling has been simplified for several methods, and the "generateTriggerURL" method no longer returns an error.
Here are the most important changes:
Add unit test for flag trigger.
Refactoring to use `v2fs` package:
* [`pkg/feature/api/api.go`](diffhunk://#diff-982bed6b45a5128e1cac0183ec37fca993ed8174a115201c70c168f63f8e9043R27-R29): Imported the `v2fs` package and its `FeatureStorage` and `FlagTriggerStorage` types. These were then added as fields to the …

test: add unit test for flag trigger

---

hack/generate-service-token/command.go
pkg/account/api/account_test.go
pkg/account/api/api_test.go
pkg/auditlog/api/api_test.go
pkg/auth/api/api.go
pkg/autoops/api/api_test.go
pkg/environment/api/api_test.go
pkg/eventcounter/api/api_test.go
pkg/experiment/api/api_test.go
pkg/feature/api/api_test.go
pkg/feature/api/segment_test.go
pkg/migration/mysql/api/api_test.go
pkg/notification/api/admin_subscription_test.go
pkg/notification/api/api_test.go
pkg/push/api/api_test.go
pkg/role/role_test.go
pkg/token/idtoken.go
pkg/token/signer_test.go

part of https://github.com/bucketeer-io/bucketeer/issues/774
~~This PR should be merged AFTER the UI is implemented** to use `is_system_admin` instead of `admin_roles` in the token~~

chore: remove admin roles from token

---

pkg/autoops/api/api.go

The `stoppedBy` is being reported as `OPS_KILL_SWITCH` when the flag is disabled by a Scheduled operation.

fix: stopped_by value being reported incorrectly

---

manifests/bucketeer/charts/event-persister-evaluation-events-evaluation-count/templates/deployment.yaml
manifests/bucketeer/charts/event-persister-evaluation-events-evaluation-count/values.yaml
pkg/eventpersister/cmd/server/server.go
pkg/eventpersister/persister/persister.go

Fixes https://github.com/bucketeer-io/bucketeer/issues/612
Part of https://github.com/bucketeer-io/bucketeer/issues/405
To reduce cost in the PubSub, I'm implementing it to update the feature flag for last-used info when the evaluation count is incremented in the `event-persister-evaluation-count`.
Note: The update and write cache code is the same as the one being used in the `feature-recorder` service.
---
This pull request introduces changes to support MySQL in the event persister service of the Bucketeer system. The changes include adding MySQL environment variables, importing the MySQL client, and adding a write cache interval. The pull request also includes improvements in error handling and logging.
Here are the top five most important changes, grouped by theme:
MySQL Support:
* …

chore: write flag last used info in the persister evaluation count

---

pkg/eventpersisterops/storage/v2/sql/count_auto_ops_rules.sql

Because the Scheduled operations are not based on events, they must not be included in the query results. Otherwise, the `event-persister-evaluation-events-ops` will subscribe to PubSUb, pulling messages unnecessarily.
Because we no longer support multiple clauses in the same rule, I will refactor the proto structure so we can add a new column to know the operations, simplifying the query, too.

fix: event persister subscribing to pubsub when running scheduled operations

---

manifests/bucketeer/charts/batch/values.yaml
pkg/batch/cmd/server/server.go
pkg/batch/jobs/cacher/apikeycacher.go
pkg/batch/jobs/cacher/autoopsrulescacher.go
pkg/batch/jobs/cacher/experimentcacher.go
pkg/batch/jobs/cacher/featureflagcacher.go
pkg/batch/jobs/cacher/segmentusercacher.go

Part of https://github.com/bucketeer-io/bucketeer/issues/820
----
This pull request primarily focuses on enhancing the logging and caching mechanisms in the batch processing system. The most significant changes include the addition of new cron jobs in the `values.yaml` file, the inclusion of a logger in various cacher functions, and the removal of timeout options in cacher initializations. Error handling has also been improved with more detailed logging messages.
Addition of new cron jobs:
* [`manifests/bucketeer/charts/batch/values.yaml`](diffhunk://#diff-da142715fb447fa09cd1b8854c0f9caa732a8d7d0555e25ae2bd0d8cb52d4b4dR138-R152): Added new cron jobs for `feature-flag-cacher`, `segment-user-cacher`, `api-key-cacher`, `experiment-cacher`, and `auto-ops-rules-cacher` with a schedule of …

chore: add cronjob for the batch cachers

---

pkg/eventcounter/api/api.go
pkg/experimentcalculator/experimentcalc/experiment_calculator.go
test/e2e/eventcounter/eventcounter_test.go

Part of https://github.com/bucketeer-io/bucketeer/issues/807
This PR will fix the flaky `eventcounter` e2e tests. [[1]](https://github.com/bucketeer-io/bucketeer/blob/main/test/e2e/eventcounter/eventcounter_test.go#L421-L436) [[2]](https://github.com/bucketeer-io/bucketeer/blob/main/test/e2e/eventcounter/eventcounter_test.go#L660-L675)
The reason of causing flaky behavior is the [reordering](https://github.com/bucketeer-io/bucketeer/blob/d9a33e4f040914002c5e43632b9762f714f289e0/pkg/experimentcalculator/experimentcalc/experiment_calculator.go#L350-L352) experiment variation results by variation id.
So we should keep the original order of experiment variations to fix this issue. [[1]](https://github.com/bucketeer-io/bucketeer/pull/845/files#diff-b0f1a6e9d024e46f089e3bc6573a1c8f6dfaf821d6b389 …

fix: experiment variation results order

---

ui/web-v2/apps/admin/src/components/AdminNotificationList/index.tsx
ui/web-v2/apps/admin/src/components/NotificationList/index.tsx
ui/web-v2/apps/admin/src/components/PushList/index.tsx

This PR fixes invalid links:
I think correct links are:
- https://docs.bucketeer.io/integration/pushes
- https://docs.bucketeer.io/integration/notifications

chore: fix invalid links pushes and notifications

---

pkg/cache/v3/in_memory_cache.go

We already using `defer` [here](https://github.com/bucketeer-io/bucketeer/pull/867/files#diff-51b4f0933cab6b08c7fbea878aa8b862fd9a6a843788c6d35f7d9207c335ed6fR49), so we can remove calling unnecessary `Stop()` in `InMemoryCache`.
```go
func (c *InMemoryCache) startEvicter(evictionInterval time.Duration) {
ticker := time.NewTicker(evictionInterval)
defer ticker.Stop()
for {
select {
case now := <-ticker.C:
c.evictExpired(now)
case <-c.doneCh:
return
}
}
}
```

chore: remove unnecessary Stop()

---

test/e2e/eventcounter/eventcounter_test.go

The `TestGetExperimentResults` takes between 3-5 minutes. During the tests, I noticed that the auto scaler rescheduled the pods, causing random errors. So, I implemented a retry logic in all the get functions to retry if an error that is not internal occurs.
It returned `NotFound` and `Unavailable` errors during the tests.
```
=== CONT  TestHTTPTrack
--- PASS: TestGetEvaluationTimeseriesCount (83.45s)
Failed to get experiment goal count. Error code: 14. Retrying in 5 seconds.
Failed to get experiment goal count. Error code: 14. Retrying in 5 seconds.
--- PASS: TestExperimentEvaluationEventCount (84.87s)
--- PASS: TestGrpcExperimentEvaluationEventCount (85.20s)
--- PASS: TestHTTPTrack (85.22s)
--- PASS: TestGrpcExperimentGoalCount (85.37s)
Failed to get experiment result. Experiment ID: …
```

test: fix possible e2e flaky test while getting experiment results

---

pkg/autoops/api/error.go
pkg/autoops/api/progressive_rollout.go
pkg/autoops/api/progressive_rollout_test.go
pkg/locale/localizedata/en.yaml
pkg/locale/localizedata/ja.yaml
pkg/locale/localizer.go

There was a validation for scheduled operations that should be removed, and the validation for running the experiment was missing.
- Removed validation for scheduled operations, creating a progressive rollout
- Added validation for waiting or running experiments when creating a progressive rollout
- Remove unused locale
---
This pull request includes changes to the `autoops` package, specifically the `progressive_rollout.go` and related test file `progressive_rollout_test.go`. The changes mainly focus on the removal of validation for auto ops rules, the addition of a check for scheduled or running experiments, and the modification of error messages.
Changes to validation and error handling:
* [`pkg/autoops/api/error.go`](diffhunk://#diff-6713b69b4756f893e138c9dc567f83d66eb192b7acc6697c1464 …

fix: cannot create a rollout when the flag has a scheduled operation

---

test/e2e/eventcounter/eventcounter_test.go

There was a bug in the retry logic, making it retry less than it was supposed to. In that case, it was 30 times.
Also, I made some improvements around the timeout and the retry logic.
Now, after retrying, it won't fail. Instead, it will return the error the caller handles and proceed accordingly.

test: fix retry logic in the event counter tests

---

pkg/eventcounter/api/api_test.go

This pull request introduces changes to the test functions in the `pkg/eventcounter/api/api_test.go` file. The changes primarily involve adding organization and environment roles to the test functions to simulate different user permissions. This will help in testing the permission handling logic of the application. 
resolves https://github.com/bucketeer-io/bucketeer/issues/809
The changes can be grouped into two main categories:
1. Addition of `orgRole` and `envRole` to test functions: These roles simulate the permissions of different users in the organization and environment respectively. They are added to the test function parameters and passed to the `newEventCounterService` function. This allows the tests to simulate different user permissions and test the permission handling logic of …

test: add PermissionDenied error test for EventCounter APIs

---

pkg/experiment/api/api_test.go
pkg/experiment/api/experiment_test.go
pkg/experiment/api/goal_test.go
pkg/notification/api/api_test.go
pkg/notification/api/subscription_test.go
pkg/push/api/api_test.go

This pull request contains changes to improve the handling of permissions and roles in the `pkg/experiment/api` and `pkg/notification/api` packages. The most significant changes include the addition of new parameters to the `createExperimentService` function, the removal of the `storage` import in `api_test.go`, and the introduction of a new `toPtr` function. 
resolves https://github.com/bucketeer-io/bucketeer/issues/809
Changes to `createExperimentService` and related functions:
* [`pkg/experiment/api/api_test.go`](diffhunk://#diff-53481da3d90c97f610a448784446e20d2900f41dfe7041a8b543aa3118fc7980L57-R75): The `createExperimentService` function now accepts new parameters for `specifiedEnvironmentId`, `specifiedOrgRole`, and `specifiedEnvRole`. These changes also affect the …

test: add PermissionDenied error test for Experiment, Notification, Push APIs

---

go.mod
go.sum
pkg/storage/v2/mysql/client.go

I'm not sure why we are using the `go-sql-driver` to convert the errors, but we are not using the driver in the client. I think we forgot to import it.
Because the `go-sql-driver` is also lightweight and faster than the standard drivers, I'm implementing the use of it.
The e2e tests also have passed.
Reference.
https://github.com/bucketeer-io/bucketeer/blob/main/pkg/storage/v2/mysql/error.go#L21

chore: use go-sql-driver in the mysql client

---

pkg/auditlog/storage/v2/admin_audit_log.go
pkg/auditlog/storage/v2/admin_audit_log_test.go
pkg/auditlog/storage/v2/audit_log.go
pkg/auditlog/storage/v2/audit_log_test.go
pkg/auditlog/storage/v2/sql/adminauditlog/insert_admin_audit_log_v2.sql
pkg/auditlog/storage/v2/sql/adminauditlog/select_admin_audit_log_v2.sql
pkg/auditlog/storage/v2/sql/adminauditlog/select_admin_audit_log_v2_count.sql
pkg/auditlog/storage/v2/sql/auditlog/insert_audit_log_v2.sql
pkg/auditlog/storage/v2/sql/auditlog/select_audit_log_v2.sql
pkg/auditlog/storage/v2/sql/auditlog/select_audit_log_v2_count.sql
pkg/storage/v2/mysql/query.go
pkg/storage/v2/mysql/query_test.go

This pull request primarily focuses on improving the code quality and maintainability of the `pkg/auditlog/storage/v2` package. The changes include the use of embedded SQL files for query strings, simplification of query construction, and updates to the corresponding tests to reflect these changes.
resolve https://github.com/bucketeer-io/bucketeer/issues/850
Here are the most important changes:
Embedding SQL files and using them in the code:
* [`pkg/auditlog/storage/v2/admin_audit_log.go`](diffhunk://#diff-cc43acba578843c53b12f2caeadc05475659808cc2221e0e25414681145f9122R32-R38): Embedded SQL files for insert, select, and count operations, and used them in the corresponding methods. [[1]](diffhunk://#diff-cc43acba578843c53b12f2caeadc05475659808cc2221e0e25414681145f9122R32-R38) …

refactor: sql query to binary files for Auditlog 

---

manifests/bucketeer/charts/batch/templates/deployment.yaml
manifests/bucketeer/charts/batch/templates/envoy-configmap.yaml
manifests/bucketeer/charts/batch/templates/subscribers-configmap.yaml
manifests/bucketeer/charts/batch/values.yaml
pkg/batch/cmd/server/server.go
pkg/batch/subscriber/processor/domain_event_informer.go
pkg/batch/subscriber/processor/metrics.go
pkg/batch/subscriber/processor/processors.go
pkg/batch/subscriber/processor/segment_persister.go
pkg/batch/subscriber/processor/segment_user_persister.go
pkg/batch/subscriber/subscriber.go

This PR will move the feature-segment-persister to the batch service. Additionally, it will add support for custom `Processor` parameters in the multi pubsub architecture.
- Create a new json configmap for the `Processor`: [[1]](https://github.com/bucketeer-io/bucketeer/pull/896/files#diff-186ceb07184707bd9312a6f564dde8b86c7025ad9a3fd7d74e2688860f64c12aR14-R16) [[2]](https://github.com/bucketeer-io/bucketeer/pull/896/files#diff-da142715fb447fa09cd1b8854c0f9caa732a8d7d0555e25ae2bd0d8cb52d4b4dR176-R180)
- Parse `Processor` json config: [[1]](https://github.com/bucketeer-io/bucketeer/pull/896/files#diff-9f3bffbf9b659d0228f7f25aeb18a14d9fa79a72e2a8100e7371b1d112faa00cR615-R629) [[2]](https://github.com/bucketeer-io/bucketeer/pull/896/files#diff-9f3bffbf9b659d0228f7f25aeb18a14d9fa79a72e2a8100e7 …

feat: move segment persister to batch service

---

pkg/gateway/api/api.go
pkg/gateway/api/api_grpc.go
pkg/gateway/api/api_test.go

I'm adding logs to track when a request fails while trying to check the API key.
- Added logs for checking API key
- Added logs for validating the request
---
This pull request primarily focuses on error handling and logging improvements in the `pkg/gateway/api` package. The changes enhance the error logging by including more context-specific details. In addition, the request validation process has been restructured in several functions, moving the `checkRequest` call after the request body decoding. Test cases have also been updated to reflect these changes.
Here are the most important changes:
Error Handling and Logging Improvements:
* [`pkg/gateway/api/api.go`](diffhunk://#diff-aeacd2d921540b49d9dde22d96b46c3f4c440e735314e2e1d9dec9a9b26c1940L400-L403): Enhanced error logging in …

chore: add error logs when checking requests in the api-gateway

---

pkg/autoops/api/api.go
pkg/autoops/api/flag_trigger_operation.go
pkg/autoops/api/flag_trigger_operation_test.go

Fixes https://github.com/bucketeer-io/bucketeer/issues/913
---
This pull request includes changes in the `pkg/autoops/api` package to improve the handling of feature flag operations and to simplify the codebase. The major changes include refactoring the `ExecuteAutoOps` function and the `executeAutoOpsRuleOperation` function, and adding tests for the `enableFeature` and `disableFeature` functions.
Refactoring of functions:
* [`pkg/autoops/api/api.go`](diffhunk://#diff-13112ed94680ecaec33373531ff5c65e48cecae142657203e04d967a185684d5R1006-R1014): In the `ExecuteAutoOps` function, the `autoOpsRule` parameter has been replaced with `autoOpsRule.OpsType` and `ftStorage` has been added. The error message has been updated to reflect the changes.
* …

fix: infinite loop when trying to enable/disable a flag when using auto operation

---

manifests/bucketeer/charts/batch/templates/cronjob.yaml

Because the jobs run every minute, if they fail due to network or unavailable errors, we can ignore them because they are temporary.
000 = Network issues (Host not found, etc)
503 = Can happen when the pods are being terminated

chore: change cronjob error code condition to ignore 503 and 000 errors

---

pkg/cache/v3/environment_api_key.go
pkg/gateway/api/api.go
pkg/gateway/api/api_grpc.go
pkg/gateway/api/api_grpc_test.go
pkg/gateway/api/api_test.go
pkg/gateway/cmd/server.go

Fixes https://github.com/bucketeer-io/bucketeer/issues/935
We have been experiencing instability issues when the in-memory cache is gone and trying to get the environment API from MySQL. Since the Memorystore has a higher SLA than CloudSQL, I have changed it to Redis.
The batch service already updates the environment API key cache every minute.
This will increase the response latency by a few milliseconds, but it will bring more stability.

chore: change to use redis to cache environment api key

---

pkg/user/persister/persister.go
pkg/user/persister/persister_test.go
pkg/user/storage/v2/mau.go
pkg/user/storage/v2/mock/mau.go

The current implementation is too slow when upserting the same row into the DB.
Instead of upserting a single value, I have changed to upserting multiple values in a single query, which is far faster.
The multiple values in a single query logic, is the same logic being used in the [segment user persister](https://github.com/bucketeer-io/bucketeer/blob/main/pkg/feature/storage/v2/segment_user.go#L78).
Before: 9k messages per second
After 40k messages per second
---
This pull request modifies the `persister.go` and `persister_test.go` files in the `pkg/user/persister` package, and the `mau.go` file in the `pkg/user/storage/v2` package. The changes primarily focus on improving the handling of user events and messages, and upserting multiple user events in batches. 
Here are the most …

perf: implement multiple upserting for user persister

---

pkg/batch/subscriber/processor/user_event_persister.go

This pull request will fix the issue of the `logger` field not being set, which has caused the user event persister to stop subscription.

fix: nil pointer when logging

---

manifests/bucketeer/charts/batch/templates/deployment.yaml
manifests/bucketeer/charts/batch/values.yaml
pkg/batch/cmd/server/server.go

After we moved the user persister to the batch service, many requests got stuck when upserting the values in the DB. It was getting context deadline errors.
The reason was the MySQL client, by default, uses 10 connections, and the user persister uses 10 workers.
Also, there are other services that use the same client instance, which causes delays in the operations in MySQL, causing errors.
For now, I'm setting the default value to 50 connections. But we should be careful when moving or adding new services that use MySQL in the future.

chore: add mysql open connection configuration to batch server

---

pkg/gateway/api/api_grpc.go
pkg/gateway/api/api_grpc_test.go

Part of #921 
The register events API must also accept requests using the `SERVER_SDK` API role so the new server SDK can report events correctly.

chore: change to allow server api role in the register events api

---

pkg/gateway/api/api_grpc_test.go

Sometimes `RequestedAt` is not the value as expected.

test: fix flaky tests

---

.devcontainer/devcontainer.json
.github/.devcontainer/Dockerfile
.github/.devcontainer/devcontainer-lock.json
.github/.devcontainer/devcontainer.json
Makefile

This PR
- Enables to development of Bucketeer inside devcontainers.
- Update dependencies
- Add tools
- clang-format
- Install tools after the container starts
- Add make command
- `build-devcontainer` builds devcontainer locally. This command is for development of devcontainer.

chore: fix devcontainer for development

---

.github/workflows/pr-go.yaml
proto/.clang-format
proto/notification/recipient.proto

The `ubuntu-latest` uses clang-format 14, which is very old. 
Sometimes, it fails due to a newer version running on the local machine when developing.
To avoid this, I'm setting a specific version to avoid errors.

ci: set clang-format version

---

Makefile
manifests/localenv/values.yaml

Fixed #1009 
- Bigquery emulator support arm cpu
- Remove all peristers deployment since all of them were moved to `batch` service

chore: bigquery emulator support arm cpu

---

manifests/localenv/values.yaml

We will manage the bigquery emulator in Bucketeer: https://github.com/bucketeer-io/bigquery-emulator/pkgs/container/bigquery-emulator

chore: change bigquery emulator image to bucketeer

---

pkg/autoops/storage/v2/auto_ops_rule.go
pkg/autoops/storage/v2/sql/auto_ops_rule/insert_auto_ops_rule.sql
pkg/autoops/storage/v2/sql/auto_ops_rule/select_auto_ops_rule.sql
pkg/autoops/storage/v2/sql/auto_ops_rule/select_auto_ops_rules.sql
pkg/autoops/storage/v2/sql/auto_ops_rule/update_auto_ops_rule.sql

This pull request includes Storage layer support needed in the process of supporting multiple schedules for automated operations.
The related RFC is https://github.com/bucketeer-io/bucketeer/pull/937.
Part of https://github.com/bucketeer-io/bucketeer/issues/885.
As a result of this PR, we need to add a column of `status` to the `auto_ops_rule` table.
```
ALTER TABLE auto_ops_rule
ADD `status` int NOT NULL default 0;
```
Changes to SQL queries:
* [`pkg/autoops/storage/v2/sql/auto_ops_rule/insert_auto_ops_rule.sql`](diffhunk://#diff-49b2f47566150a206e986802da795ae502851cf3296d080db4ee50cd653c0008R10-R13): Added a new `status` field to the `INSERT INTO auto_ops_rule` SQL command.
* [`pkg/autoops/storage/v2/sql/auto_ops_rule/select_auto_ops_rule.sql`](diffhunk://#diff-a4ff36c09f4785224443ae20c …

chore: update storage for multi-schedule

---

.github/dependabot.yaml

release please can be the target now (https://github.com/bucketeer-io/bucketeer/pull/987)

ci: remove dependabot ignoring release please

---

.github/dependabot.yaml

The UI's packages were recently cleaned up (https://github.com/bucketeer-io/bucketeer/pull/1031, https://github.com/bucketeer-io/bucketeer/pull/1039), so I suppose they're ready to be updated with Dependabot.

ci: update npm packages with dependabot

---

ui/web-v2/eslint.config.mjs
ui/web-v2/src/components/CreatableSelect/index.tsx
ui/web-v2/src/components/DateRangePopover/index.tsx
ui/web-v2/src/components/OperationAddUpdateForm/index.tsx
ui/web-v2/src/components/Select/index.tsx
ui/web-v2/src/components/TimeseriesAreaLineChart/index.tsx
ui/web-v2/src/components/VariationInput/index.tsx
ui/web-v2/src/config/index.ts
ui/web-v2/src/pages/experiment/formSchema.ts
ui/web-v2/src/pages/feature/formSchema.ts
ui/web-v2/src/pages/feature/targeting.tsx
ui/web-v2/src/pages/feature/variations.tsx

part of https://github.com/bucketeer-io/bucketeer/issues/1017

chore: enable typescript-eslint/no-explicit-any

---

DEVELOPMENT.md
Makefile

For now, I'm reverting this because the e2e test fails in the CI due to incorrect file paths.
I'll think of a better of doing this.

revert: default vars for dev container

---

go.mod
go.sum
pkg/feature/domain/feature.go
pkg/feature/domain/feature_test.go

proto built-in Clone() changes an empty slice to nil, which creates unexpected diffs.

fix: proto clone changs empty slice to nil

---

pkg/token/verifier.go

Part of https://github.com/bucketeer-io/bucketeer/pull/1097
Because the issuer was different when using Dex, we had to stop verifying the issuer and audience until we updated the new issuer and audience using the new authenticator.

chore: change to verify issuer and audience in the access token

---

manifests/bucketeer-migration/templates/atlas-migration.yaml
manifests/bucketeer-migration/values.yaml
manifests/bucketeer/templates/atlas-migration.yaml
manifests/bucketeer/values.yaml

The current setting is 24 hours. After the Job is deleted, PipeCD keeps showing an out-of-sync warning because the job is no longer there. So, I'm changing the `ttlSecondsAfterFinished` to be optional so we can keep the job after completion and avoid warnings.

chore: make the `ttlSecondsAfterFinished` optional in the migration job

---

pkg/auth/api/signin.go

If we disabled the demo sign-in but the demo account is still enabled, someone could get the access token by calling the SignIn API directly.
So, I changed it to check the config file to ensure we won't access it if it is disabled.

chore: improve security in the sign-in api

---

pkg/autoops/api/progressive_rollout.go
pkg/autoops/api/progressive_rollout_test.go

```
stacktrace: "github.com/bucketeer-io/bucketeer/pkg/pubsub/publisher.(*publisher).PublishMulti
/home/runner/work/bucketeer/bucketeer/pkg/pubsub/publisher/publisher.go:134
github.com/bucketeer-io/bucketeer/pkg/autoops/api.(*AutoOpsService).ExecuteProgressiveRollout
/home/runner/work/bucketeer/bucketeer/pkg/autoops/api/progressive_rollout.go:561
github.com/bucketeer-io/bucketeer/proto/autoops._AutoOpsService_ExecuteProgressiveRollout_Handler.func1
/home/runner/work/bucketeer/bucketeer/proto/autoops/service.pb.go:3108
github.com/bucketeer-io/bucketeer/pkg/rpc.(*Server).setupRPC.AuthUnaryServerInterceptor.func3
/home/runner/work/bucketeer/bucketeer/pkg/rpc/auth.go:66
google.golang.org/grpc.getChainUnaryHandler.func1
/home/runner/work/bucketeer/bucketeer/vendor/google.golang.org/grpc/server. …
```

fix: publish domain event fails due to message being nil

---

Makefile

This pull request allows the development container to function in a semi-offline mode by incorporating a command in the Makefile to pre-pull Docker images.
After a developer initiates the development container for the first time, it will already include all required images. Thereafter, developers can continue working without an internet connection by simply keeping the development container running.

chore: add pre-pull images command for dev container

---

pkg/account/api/admin_account.go
pkg/account/api/admin_account_test.go

- Fixed system admin account being redirected to the login page on non-system organizations
- Fixed showing organizations where the account is not registered or is disabled
- Fixed showing environments where the account is disabled
---
This pull request includes significant changes to the `AccountService` and its associated test suite in `admin_account.go` and `admin_account_test.go` respectively. The changes are primarily focused on refactoring the `checkAccountStatus` method into `getAccount`, which now also retrieves the account information. This change has a cascading effect on other methods and tests that used `checkAccountStatus`. Additionally, there are changes to handle account disabling and enabling, which are currently managed through the `Role` attribute but will be managed …

fix: account not found when using system admin account

---

evaluation/evaluation.go

There is a [race condition](https://github.com/bucketeer-io/go-server-sdk/actions/runs/10036619540/job/27736550399?pr=136) in the Go SDK when the variation description is removed when evaluating the user.
The evaluation module shouldn't change the data in memory.
To avoid other issues, I changed it to copy the Variation object with no description instead of changing the in-memory data.
Go SDK coverage and unit test results.
```
make test
.....
ok  	github.com/bucketeer-io/go-server-sdk/pkg/bucketeer/user	(cached)
=== RUN   TestNewV4
=== PAUSE TestNewV4
=== CONT  TestNewV4
--- PASS: TestNewV4 (0.00s)
PASS
ok  
```
```
make coverage 
go test -race -covermode=atomic -coverprofile=coverage.out -coverpkg=./pkg/... ./pkg/...
?   	github.com/bucketeer-io/go-server-sdk/pkg/bucketeer/cache/mock …
```

fix(evaluation): race condition when removing the variation description

---

.devcontainer/devcontainer.json

When building many times a day, it will increase the storage usage and fail with no space left.
So, I added the `docker system prune -f` command to delete the docker building cache to avoid that error.

chore: delete docker building cache when open dev container

---

ui/web-v2/src/components/EventRateAddUpdateForm/index.tsx
ui/web-v2/src/components/FeatureConfirmDialog/index.tsx

The action type wasn't set when creating an event rate operation. Also, it wasn't set when creating a schedule operation on the feature flags list page.

fix(ui): auto operation action type not being set

---

pkg/autoops/api/api.go
pkg/autoops/api/api_test.go
test/e2e/autoops/auto_ops_test.go

Now that the UI multi-scheduling support has been merged, it should validate Unknown Action Type.

fix: validate unknown action type

---

pkg/batch/storage/v2/auto_ops_rule.go
pkg/batch/storage/v2/mock/auto_ops_rule.go
pkg/batch/storage/v2/sql/count_auto_ops_rules.sql
pkg/batch/subscriber/processor/events_ops_persister.go
test/e2e/autoops/auto_ops_test.go

- Fixed count query
- Updated e2e tests to use the correct `ops_type and` and `action_type` when testing event rate operations.

fix: ops event rate not being processed

---

Makefile
tools/dev/Makefile

To avoid the kubectl commands for the dev container being executed on the host by accident, I changed to always executing it in the `minikube` context.

chore: ensure that all kubectl commands for the dev container run in the minikube only

---

ui/web-v2/package.json

When we build the web project, it deletes the `DONT-EDIT-FILES-IN-THIS-DIRECTORY` in the dist directory.
Because the go embed building needs that file, we must ensure it is not accidentally deleted and pushed to the main branch.

build(ui): add post build script to recreate the file after building web project

---

pkg/autoops/api/api.go
pkg/autoops/api/api_test.go
pkg/autoops/api/error.go
pkg/autoops/domain/auto_ops_rule.go

Fixed to reject requests that have the same date or already have the same date when scheduling AutoOps.

fix: validated the same date for schedule Auto Ops

---

pkg/autoops/api/flag_trigger_operation.go
pkg/gateway/api/api_grpc.go

The log cost is increasing significantly due to context canceled errors.
Since the request can be canceled by a timeout or the client canceling it, I'm changing it to ignore it.
We can still monitor the context canceled request on the Grafana.

chore: ignore context canceled errors when publishing to pubsub

---

pkg/subscriber/processor/metrics.go

Because the Subsystem is a subscriber, the metric name should not include the `subscriber` prefix.

fix: subscriber metric name

---

pkg/autoops/api/api.go

When updating an AutoOps schedule, updating to a different ActionType while keeping the same date caused an error.

fix: fixed to also check ActionType when validating the same date

---

pkg/account/storage/v2/admin_account.go
pkg/account/storage/v2/sql/account_v2/select_accounts_with_organization.sql
pkg/account/storage/v2/sql/account_v2/select_system_admin_account_v2.sql

Fix the error `sql: expected 19 destination arguments in Scan, not 20"` when getting the user account.

fix: sql argument when getting account

---

test/e2e/eventcounter/eventcounter_test.go

For some reason, the E2E test requests are failing due to timeout when running them on GitHub Actions.
It seems it works better when setting the timeout to 2 minutes.

test: increase request timeout for eventcounter tests to improve flaky tests

---

pkg/api/api/metrics_event.go

I'm adding logs to check the labels (key/value map), which contain the error message when an unknown error happens, to improve debugging.

chore: add log for error metrics from sdk client

---

pkg/auditlog/storage/v2/admin_audit_log.go
pkg/auditlog/storage/v2/admin_audit_log_test.go
pkg/auditlog/storage/v2/audit_log.go
pkg/auditlog/storage/v2/audit_log_test.go
pkg/auditlog/storage/v2/mock/admin_audit_log.go
pkg/auditlog/storage/v2/mock/audit_log.go
pkg/auditlog/storage/v2/sql/adminauditlog/insert_admin_audit_logs_v2.sql
pkg/auditlog/storage/v2/sql/auditlog/insert_audit_log_v2.sql
pkg/auditlog/storage/v2/sql/auditlog/insert_audit_logs_v2.sql
pkg/subscriber/processor/auditlog_persister.go

When the subscriber tries to insert an audit log that already exists in the DB, it doesn't acknowledge the PubSub message and keeps trying in an infinite loop until the message expires in PubSub.
I'm changing it to insert a single audit log so we can acknowledge the correct message when it happens and not all the messages in the chunk, which could lead to data loss.

fix: audit log pubg message not being acknowledged

---

ui/web-v2/src/pages/feature/evaluation.tsx

When using Redis Cluster, merging the time-series data takes more time than a single instance. Because the user usually checks a 7-day or 24-hour range more often, so I'm changing the default request to 7 days.

chore: change the default time range when getting evaluation count to 7 days

---

pkg/feature/api/feature.go

If error is nil and feature == nil is true, then returned error is nil, (log nil error of course). This pr return the correct error

fix: err is nil when the flag is not found in the update feature api

---

.github/workflows/push-image.yaml

Fixes [https://github.com/bucketeer-io/bucketeer/security/code-scanning/1](https://github.com/bucketeer-io/bucketeer/security/code-scanning/1)
To fix the problem, we need to avoid using the user-controlled input directly in the shell command. Instead, we should set the untrusted input value to an intermediate environment variable and then use the environment variable in the shell command using the native shell syntax. This approach will prevent command injection vulnerabilities.
Specifically, we will:
1. Set the commit message to an environment variable.
2. Use the environment variable in the shell command to safely extract the first line of the commit message.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

ci: fix expression injection in action workflow

---

tools/gen/descriptor.sh

Resolve issue https://github.com/bucketeer-io/bucketeer/issues/1328
- At one point when we specify new API or develop new feature in *.proto files, the proto_descriptor.pb (in /proto sub packages) will expand.
- **For some machines**, the input argument when we run bash commands will reach that machine max arg limitation, so when we run make go-descriptor or make generate-all, the error "Argument list too long" can appear in line 33 in tools/descriptor.sh, hence we can not replace the encoded-descriptor in manifest.envoy descriptor yaml config and block the rest.
```bash
/workspaces/bucketeer/tools/gen/descriptor.sh: line 33: /go/bin/yq: Argument list too long
make[1]: *** [Makefile:89: go-descriptor] Error 126
make[1]: Leaving directory '/workspaces/bucketeer/proto'
make: *** …
```

fix: use file io encoded_descriptor when replace encoded descriptor

---

migration/README.md
migration/mysql/20241122095236_sync_api_key_table.sql
migration/mysql/atlas.sum

Part of https://github.com/bucketeer-io/bucketeer/issues/1331
- Add doc for manual atlas migration
- Populate api_key with values from id

chore: populate api_key with values from id

---

pkg/subscriber/processor/evaluation_events_evaluation_count_event_persister.go
pkg/subscriber/processor/metrics.go

This pull request includes changes to the evaluation event metrics in the `pkg/subscriber/processor` package to improve the tracking of variation IDs. The most important changes are:
Metrics update:
* [`pkg/subscriber/processor/evaluation_events_evaluation_count_event_persister.go`](diffhunk://#diff-ce8f25bdc00abed88c31fe33f370739972f110b61246643d20d74286ad81799aL258-R258): Modified the `incrementEvaluationCount` function to include `VariationId` in the `evaluationEventCounter` labels.
* [`pkg/subscriber/processor/metrics.go`](diffhunk://#diff-097770a75bd6749152b599e44f98b7dca77d92b833fecbfea9c2ce40291607ffL90-R90): Updated the `evaluation_event_total` metric definition to include `variation_id` as a label.

fix: update evaluation event counter metrics to include variation ID

---

pkg/cache/cache.go
pkg/cache/mock/cache.go
pkg/cache/testing/cache.go
pkg/cache/v3/redis_cache.go
pkg/redis/v3/mock/redis.go
pkg/redis/v3/redis.go

Part of https://github.com/bucketeer-io/bucketeer/issues/1368
I am adding transaction support so we can ensure that we don't duplicate the counting when an error occurs, saving the counts in the same request in the subscriber svc.

chore: add transaction support for redis pipeline

---

pkg/redis/v3/redis.go
pkg/subscriber/processor/evaluation_events_evaluation_count_event_persister.go

I tried using Pipeline, and indeed, it improves the response time, but it also increases the Pod CPU usage. It's a trade-off.
Since this is a background service and it's not latency-sensitive, I'm reverting it.

revert: change to save user and event counts in one request

---

migration/mysql/20241206094413_sync_maintainer_api_key_table.sql
migration/mysql/atlas.sum

Part of https://github.com/bucketeer-io/bucketeer/issues/1331
- Get creator of api key from audit_log table and update api_key.maintainer so audit log issue can also be resolved for old api keys

chore: create sync api key maintainer migration

---

pkg/subscriber/processor/push_sender.go

I see a `Failed to update segment user cache` error due to `context deadline exceeded` while trying to send the FCM notification.
Since this process involves many internal requests and could take more than 30 seconds, depending on some cases, I'm changing it to 1 minute to see how it goes.

chore: change update segment cache timeout to 1 minute

---

.golangci.yml
hack/create-big-query-table/command.go
hack/create-big-query-table/main.go
hack/redis-data-copy/command.go
hack/redis-data-copy/main.go
pkg/api/api/account.go
pkg/api/api/metrics_event.go
pkg/api/api/register_event_type.go
pkg/auth/api/validation.go
pkg/auth/error.go
pkg/auth/google/authenticator.go
pkg/auth/interface.go
pkg/batch/jobs/mau/mau_partition_deleter.go
pkg/batch/jobs/mau/mau_summarizer.go
pkg/cache/v3/in_memory_cache.go
pkg/crypto/hashicorpvaultcrypto.go
pkg/redis/v3/crc16.go
pkg/subscriber/processor/metrics_event_persister.go

This repository uses the Apache License Version 2.0, and each file has the license header.
I think it's nice to ensure this with the linter because someone may mistakenly make a file with no header.

chore: add linter to ensure lisence header

---

pkg/rpc/server.go

The application level is already logging the most important warning and error logs; I'm removing this from the RPC layer because there are too many duplicate logs, unnecessarily increasing the log costs in GCP.

chore: remove grpc logging

---

pkg/notification/api/subscription.go
ui/web-v2/src/modules/notifications.ts
ui/web-v2/src/pages/notification/index.tsx

Fix #1420 
The list API listed all subscriptions in the organization, so when we tried to update a subscription that was not in the currently selected environment, it failed because it could not be found.

fix(ui): subscription not found when updating

---

pkg/auth/api/signin.go

Fixes [https://github.com/bucketeer-io/bucketeer/security/code-scanning/7](https://github.com/bucketeer-io/bucketeer/security/code-scanning/7)
To fix the problem, we should avoid logging the password entirely. Instead, we can log other non-sensitive information that can help in debugging or monitoring without exposing sensitive data. In this case, we can remove the logging of the password and retain the logging of other relevant information such as the email and whether the sign-in feature is enabled.
- Remove the line that logs the password.
- Ensure that the functionality remains unchanged by only modifying the logging statement.
- The changes will be made in the file `pkg/auth/api/signin.go` on line 45.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

fix: clear-text logging of sensitive information

---

pkg/experiment/storage/v2/sql/goal/select_goal.sql

query in select_goal.sql should be JSON_ARRAYAGG instead of GROUP_CONCAT
Reference: `error: "sql: Scan error on column index 9, name "experiments": unexpected end of JSON input"`

fix: query in select goal api

---

pkg/autoops/api/api.go
pkg/autoops/api/api_test.go
pkg/autoops/api/progressive_rollout.go
pkg/autoops/api/progressive_rollout_test.go
pkg/autoops/storage/v2/auto_ops_rule.go
pkg/autoops/storage/v2/auto_ops_rule_test.go
pkg/autoops/storage/v2/progressive_rollout.go
pkg/autoops/storage/v2/progressive_rollout_test.go
pkg/feature/api/feature.go
pkg/feature/api/feature_test.go
pkg/storage/v2/mysql/client.go
pkg/storage/v2/mysql/mock/client.go

This pull request includes significant changes to the `AutoOpsService` and `ProgressiveRollout` functionalities, focusing on refactoring the transaction handling mechanism. The primary change is the transition from using `RunInTransaction` to `RunInTransactionV2`, which simplifies the transaction management and improves code maintainability.
Part of https://github.com/bucketeer-io/bucketeer/issues/1252

refactor: changes to storage-related transaction handling within AutoOps packages

---

pkg/notification/api/admin_subscription.go
pkg/notification/api/admin_subscription_test.go
pkg/notification/api/api.go
pkg/notification/api/api_test.go
pkg/notification/api/subscription.go
pkg/notification/api/subscription_test.go
pkg/notification/storage/v2/admin_subscription.go
pkg/notification/storage/v2/admin_subscription_test.go
pkg/notification/storage/v2/subscription.go
pkg/notification/storage/v2/subscription_test.go

This pull request includes significant updates to the `NotificationService` in the `pkg/notification/api/admin_subscription.go` file, focusing on improving transaction handling and refactoring storage interactions. Additionally, corresponding changes have been made to the test files to align with these updates.
Improvements to transaction handling:
* [`pkg/notification/api/admin_subscription.go`](diffhunk://#diff-c5d32f9d198e39c37106414c33b9e77ae9bcfe363249aeebd24a68f3d6c229e8L68-R69): Replaced `BeginTx` and `RunInTransaction` with `RunInTransactionV2` to streamline transaction management and error handling. [[1]](diffhunk://#diff-c5d32f9d198e39c37106414c33b9e77ae9bcfe363249aeebd24a68f3d6c229e8L68-R69) [[2]](diffhunk://#diff-c5d32f9d198e39c37106414c33b9e77ae9bcfe363249aeebd24a68f3d6c229e8L …

refactor: changed transaction handling related to Notification package

---

pkg/push/api/api.go
pkg/push/api/api_test.go
pkg/push/storage/v2/push.go
pkg/push/storage/v2/push_test.go

This pull request includes significant changes to the `pkg/push/api/api.go` file to refactor transaction handling and improve the push storage mechanism. The main changes involve replacing the old transaction methods with a new version and updating the push storage usage across various functions. Additionally, the test cases in `pkg/push/api/api_test.go` have been updated to reflect these changes.
Refactoring transaction handling and push storage:
* [`pkg/push/api/api.go`](diffhunk://#diff-927c02bd692b9ee775cb3720ede88aa16612d46cf46213f45274a0ddd792c782L186-R189): Replaced the old transaction handling methods with `RunInTransactionV2` and updated the usage of `pushStorage` across multiple functions such as `CreatePush`, `UpdatePush`, `DeletePush`, and `GetPush`. …

refactor: changed transaction handling related to Push package

---

pkg/autoops/api/api.go
pkg/autoops/api/api_test.go
pkg/autoops/api/progressive_rollout_test.go
pkg/batch/api/api_test.go
pkg/batch/jobs/opsevent/event_count_watcher_test.go
pkg/opsevent/storage/v2/ops_count.go
pkg/opsevent/storage/v2/ops_count_test.go

I Changed the transaction instance of `OpsCountStorage` to be controlled via `mysqlClient.Qe()`.
Also, this pull request introduces significant updates to the `AutoOpsService` in the `pkg/autoops/api/api.go` file, focusing on the refactoring of storage dependencies. The main changes involve replacing inline storage initializations with pre-initialized storage fields within the `AutoOpsService` struct. Additionally, corresponding test updates have been made to accommodate these changes.
By doing so, you can mock Storage in your test code, resulting in more meaningful test code.
Part of #1252

refactor: changed transaction handling related to OpsEvent package

---

pkg/experiment/api/api.go
pkg/experiment/api/api_test.go
pkg/experiment/api/experiment.go
pkg/experiment/api/experiment_test.go
pkg/experiment/api/goal.go
pkg/experiment/api/goal_test.go
pkg/experiment/storage/v2/experiment.go
pkg/experiment/storage/v2/experiment_test.go
pkg/experiment/storage/v2/goal.go
pkg/experiment/storage/v2/goal_test.go

This pull request introduces significant changes to the `experimentService` in the `pkg/experiment/api` package. The main focus is on integrating the new `ExperimentStorage` and `GoalStorage` components, as well as updating the transaction handling mechanism. The changes also include updates to the corresponding tests to mock the new storage components.
Part of [#1474](https://github.com/bucketeer-io/bucketeer/issues/1474)

refactor: changed transaction handling related to Experiment package

---

pkg/account/api/account.go
pkg/account/api/account_test.go
pkg/account/api/api.go
pkg/account/api/api_key.go
pkg/account/api/api_key_test.go
pkg/account/api/api_test.go
pkg/account/api/search_filter_test.go
pkg/account/storage/v2/account.go
pkg/account/storage/v2/account_test.go
pkg/account/storage/v2/admin_account.go
pkg/account/storage/v2/admin_account_test.go
pkg/account/storage/v2/api_key.go
pkg/account/storage/v2/api_key_test.go
pkg/account/storage/v2/mock/storage.go
pkg/account/storage/v2/storage.go
pkg/autoops/command/auto_ops_rule.go
pkg/autoops/command/command.go
pkg/batch/api/api_test.go
pkg/experiment/api/goal.go

This pull request includes significant changes to the `pkg/account/api/account.go` file, focusing on updating transaction handling and integrating audit log creation. Additionally, it includes corresponding updates to the test file `pkg/account/api/account_test.go`.
Part of https://github.com/bucketeer-io/bucketeer/issues/1474
Part of #1002

refactor: changed transaction handling related to Account package

---

evaluation/typescript/package.json
evaluation/typescript/src/evaluation.ts
evaluation/typescript/src/index.ts

Part of https://github.com/bucketeer-io/bucketeer/issues/1552
This pull request includes changes to update the version of the `@bucketeer/evaluation` package and refactor a function name for clarity in the `evaluation/typescript` module. The most important changes include updating the package version and renaming the `featureIDsDependsOn` function to `getFeatureIDsDependsOn`.
Version update:
* [`evaluation/typescript/package.json`](diffhunk://#diff-4e552c36cddb498024f82e0b6a55d75319b249ba56b576a447ad0541aba84e8fL3-R3): Updated the package version from `0.0.1` to `0.0.2`.
Function refactoring:
* [`evaluation/typescript/src/evaluation.ts`](diffhunk://#diff-9066692683b621001ceee806082359c858e133563baba9d06b0aeb44966ddd09L289-R289): Renamed the function `featureIDsDependsOn` to …

chore(evaluation/typescript): export function getFeatureIDsDependsOn

---

docs/rfcs/move-i18n-logic-to-frontend.md

This pull request proposes moving the i18n (internationalization) logic entirely to the frontend to simplify the backend code. The changes include adding detailed documentation and examples of the new error handling design using GRPC's `ErrorInfo` and removing the existing `LocalizedMessage` code from the backend.
https://github.com/bucketeer-io/bucketeer/issues/1253

docs: add rfc for move i18n logic to frontend

---

evaluation/typescript/CHANGELOG.md
evaluation/typescript/Makefile
evaluation/typescript/package.json
evaluation/typescript/tsconfig.json

This pull request includes several changes to enhance the build process and ensure stricter type checking on the generated code
* [`evaluation/typescript/Makefile`](diffhunk://#diff-955290520a7032b83d1a07ab890a0248dbc3732261fb21ae36d66af8418586b9L107-R107): Add import experiment.proto, account.proto, push.proto, notification.proto...
* [`evaluation/typescript/package.json`](diffhunk://#diff-4e552c36cddb498024f82e0b6a55d75319b249ba56b576a447ad0541aba84e8fL3-R3): Updated the package version from `0.0.2` to `0.0.3`.
* [`evaluation/typescript/tsconfig.json`](diffhunk://#diff-e5ec89107a2e4807496305971d410256be6a5f4e7302a0e33041508f457b0065L28-R28): Changed the `skipLibCheck` option from `true` to `false` to enforce stricter type checking.

fix(evaluation/typescript): missing proto import when build release lib

---

pkg/subscriber/processor/metrics_event_persister.go

fix #1317
Fix unnecessary error logging for unknown API ID(issue #1317) by preventing unnecessary error logging when "unknown api id" errors occur during metrics event processing. This error is actually part of the normal flow and should not be treated as actual errors in the logs.

fix: add unknown api id error handling

---

pkg/domainevent/domain/url.go

fix #1192
- URL of autoops page is `https://ENDPOINT/production/features/hoge/autoops`

fix: update AutoOps rule URL template path

---

docs/rfcs/new-storage-architecture.md

The main goal is to remove the mysql dependency from the API layer, and we suggest a solution by modifying the storage layer architecture. #1252

docs: add rfc for storage architecture

---

pkg/coderef/api/error.go
pkg/coderef/api/validation.go

Because we have an environment in production that has an empty `environment_id`, we can't validate it. Otherwise, all the code references API will fail for that specific environment

fix: remove `environment_id` validation from code references api

---

pkg/autoops/api/api.go
pkg/autoops/api/api_test.go
pkg/autoops/api/progressive_rollout.go
pkg/autoops/api/stop_progressive_rollout_operation.go
pkg/autoops/storage/v2/auto_ops_rule.go
pkg/autoops/storage/v2/auto_ops_rule_test.go
pkg/autoops/storage/v2/mock/auto_ops_rule.go
pkg/autoops/storage/v2/mock/progressive_rollout.go
pkg/autoops/storage/v2/progressive_rollout.go
pkg/autoops/storage/v2/progressive_rollout_test.go
pkg/autoops/storage/v2/sql/auto_ops_rule/select_auto_ops_rules.sql
pkg/autoops/storage/v2/sql/ops_progressive_rollout/count_ops_progressive_rollouts.sql
pkg/autoops/storage/v2/sql/ops_progressive_rollout/select_ops_progressive_rollouts.sql
pkg/feature/api/feature.go
pkg/storage/v2/mysql/query.go
pkg/storage/v2/mysql/query_test.go

This pull request includes significant refactoring to improve the handling of query filters and options in the `AutoOpsService` and related storage components. The changes focus on replacing the existing `WherePart` and `Order` structures with a more flexible `ListOptions` structure, which encapsulates various filter types and query options.
Part of https://github.com/bucketeer-io/bucketeer/issues/1475

refactor: change the method of specifying query conditions  for AutoOps

---

ui/web-v2/src/assets/lang/ja.json
ui/web-v2/src/components/GoalList/index.tsx
ui/web-v2/src/lang/messages.ts

fix #1157
I have disabled the button so that it cannot be archived when in use, just like the `experiment` UI. 
This is how it looks.
In English
In Japanese

feat(ui/goal): add archive action tooltip and disable archive action for goals in use

---

pkg/auth/api/api.go
pkg/web/cmd/server/server.go

fix #1579
- Changed default refresh token TTL  from 1 hour to 7 days
- Added explicit WithRefreshTokenTTL() in service initialization
In the `generateToken` function, there was logic to set a default 30-day TTL but override it with the options value if present:
```go
refreshTokenTTL := 30 * day
if s.opts.refreshTokenTTL > 0 {
refreshTokenTTL = s.opts.refreshTokenTTL
}
```
However, the `defaultOptions` had the refresh token TTL set to just 1 hour:
```go
var defaultOptions = options{
refreshTokenTTL: time.Hour,
logger:          zap.NewNop(),
}
```
And the service initialization did not explicitly specify the WithRefreshTokenTTL option, so the default 1-hour value was used.
The condition `if s.opts.refreshTokenTTL > 0` was always true, causing the default 30-day setting to always be …

fix: update refresh token TTL to 7 days

---

test/e2e/experiment/experiment_test.go

Fix e2e test error when upgrading Go1.24 :
```
Error: test/e2e/experiment/experiment_test.go:597:13: non-constant format string in call to (*testing.common).Fatalf
Error: test/e2e/experiment/experiment_test.go:656:13: non-constant format string in call to (*testing.common).Fatalf
Error: test/e2e/experiment/experiment_test.go:708:13: non-constant format string in call to (*testing.common).Fatalf
```

test: fix non-constant format string in Fatalf

---

.github/workflows/code-butler.yaml
.github/workflows/devcontainer-image-build.yaml
.github/workflows/pr-evaluation-ts.yaml
.github/workflows/pr-go.yaml
.github/workflows/pr-ui-dashboard.yaml
.github/workflows/pr-ui-web.yaml
.github/workflows/publish_chart.yaml
.github/workflows/push-image.yaml
.github/workflows/update-changelog-docs-page.yml

Updates all GitHub Actions references from version tags to specific commit hashes.
- Replaced all version tags with exact commit SHAs.
- Added version comments for future reference.
ref: [Harden-Runner detection: tj-actions/changed-files action is compromised - Recovery Steps](https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised#recovery-steps)

ci: pin versions of actions to commit hashes

---

ui/web-v2/src/assets/lang/en.json
ui/web-v2/src/assets/lang/ja.json
ui/web-v2/src/components/FeatureVariationsForm/index.tsx
ui/web-v2/src/lang/messages.ts

fix #1257 
- Added support for validation of variations used in targeting rules.
When the rule in use,
In English
In Japanese

fix(ui): add error message when trying to delete a variation in use

---

test/e2e/feature/feature_test.go

The TestListFeaturesOrderByName test started failing because the ordering in MySQL is case-insensitive, but the `sort.Reverse` is case-sensitive. There is an archived flag in the e2e environment (Test JSON Flag 3), which was created today and caused the issue.

test: fix flaky feature e2e test when using case-sensitive strings

---

pkg/batch/jobs/opsevent/event_count_watcher.go
ui/web-v2/src/components/FeatureAutoOpsRulesForm/index.tsx

The evaluation and goal events are sent from the client SDK, and for many reasons, those events could get lost in the client.
So, I implemented clamping the computed rate so that it never exceeds 100% (i.e., 1.0). In other words, if you detect that the opsCount is greater than the evaluationCount, it will adjust the opsCount to be equal to the evaluationCount before calculating the rate. This way, you avoid a rate above 1.0, and the downstream logic stays consistent.
Fix https://github.com/bucketeer-io/bucketeer/issues/1607

fix: ops count is unexpectedly greater than evaluation count

---

pkg/account/storage/v2/account.go
pkg/account/storage/v2/account_test.go
pkg/account/storage/v2/admin_account.go
pkg/account/storage/v2/admin_account_test.go
pkg/account/storage/v2/api_key.go
pkg/account/storage/v2/api_key_test.go
pkg/account/storage/v2/storage.go
pkg/batch/api/api_test.go

This pull request includes changes to the `pkg/account/storage/v2` package, focusing on refactoring the database query execution to use a simpler and more direct approach. The changes also include updates to the corresponding tests to align with the new approach.
This PR is a refactor to the deprecation of `Qe()` in the PR below.
#1549

refactor: change the Account storage scope to QueryExecer

---

pkg/notification/storage/v2/admin_subscription.go
pkg/notification/storage/v2/admin_subscription_test.go
pkg/notification/storage/v2/subscription.go
pkg/notification/storage/v2/subscription_test.go

This pull request includes significant refactoring of the `admin_subscription` and `subscription` storage interfaces to replace the `mysql.Client` with `mysql.QueryExecer`. This change affects various methods and their corresponding tests.
This PR is a refactor to the deprecation of `Qe()` in the PR below.
https://github.com/bucketeer-io/bucketeer/pull/1549

refactor: change the Notification storage scope to QueryExecer

---

pkg/autoops/api/progressive_rollout.go
pkg/autoops/api/progressive_rollout_test.go
pkg/autoops/storage/v2/auto_ops_rule.go
pkg/autoops/storage/v2/auto_ops_rule_test.go
pkg/autoops/storage/v2/progressive_rollout.go
pkg/autoops/storage/v2/progressive_rollout_test.go

This pull request focuses on refactoring the `AutoOpsService` and related storage classes to simplify the codebase and improve maintainability. The primary changes involve replacing direct instantiations of `ProgressiveRolloutStorage` and `AutoOpsRuleStorage` with dependency injections, thus improving the code's flexibility and testability.
This PR is a refactor to the deprecation of `Qe()` in the PR below.
#1549

refactor: change the AutoOps storage scope to QueryExecer

---

pkg/batch/api/api_test.go
pkg/batch/jobs/opsevent/event_count_watcher_test.go
pkg/opsevent/storage/v2/ops_count.go
pkg/opsevent/storage/v2/ops_count_test.go

This pull request includes changes to the `pkg/opsevent/storage/v2/ops_count.go` file and its associated test file to replace the `mysql.Client` dependency with `mysql.QueryExecer`. This change simplifies the interface and improves the code's flexibility.
This PR is a refactor to the deprecation of Qe() in the PR below.
https://github.com/bucketeer-io/bucketeer/pull/1549

refactor: change the OpsEvent storage scope to QueryExecer

---

pkg/push/storage/v2/push.go
pkg/push/storage/v2/push_test.go

This pull request includes changes to the `pkg/push/storage/v2/push.go` and `pkg/push/storage/v2/push_test.go` files to replace the `mysql.Client` with `mysql.QueryExecer` in the `pushStorage` struct and its associated methods. The most important changes include updating the `pushStorage` struct, modifying the methods to use the new `qe` field, and adjusting the tests accordingly.
This PR is a refactor to the deprecation of `Qe()` in the PR below.
https://github.com/bucketeer-io/bucketeer/pull/1549

refactor: change the Push storage scope to QueryExecer

---

pkg/api/client/credentials.go
test/e2e/eventcounter/eventcounter_test.go
test/e2e/util/rest.go

`ioutil` pakcage is deprecated. 
We should use package io or package os instead.
https://pkg.go.dev/io/ioutil

chore: replace deprecated ioutil

---

pkg/api/api/api_grpc_test.go
pkg/api/api/grpc_validation.go
pkg/api/api/grpc_validation_test.go
pkg/api/api/metrics.go

fix #1614 
- This PR adds validation for required fields in EvaluationEvent and GoalEvent to ensure all essential data is present before processing.
- When running experiments, evaluation and goal events are saved to BigQuery. Older SDK versions may send events with missing required fields, causing: #1614

chore: validate events from the sdk in api gateway

---

pkg/feature/api/feature.go

Fix ambiguous column in whereparts
```
"message":"Failed to get feature","serviceContext":{"service":"bucketeer-web.server","version":"-"}
"error":"Error 1052 (23000): Column 'id' in where clause is ambiguous"
```

fix: ambiguous column in get features

---

ui/dashboard/src/pages/notifications/page-loader.tsx

When clicking on the name or on the button in the action menu, nothing happens.
Fix: #1632

fix(ui/dashboard): can't update a slack integration

---

evaluation/go/clause_evaluator.go
evaluation/go/clause_evaluator_test.go

fix #1248 
Updated the `parseSemver` function to maintain consistency when comparing semantic versions by:
1. Detecting if the target value has a 'v' prefix
2. When the target has a 'v' prefix, only comparing it with values that also have a 'v' prefix
3. When the target doesn't have a 'v' prefix, only comparing it with values without a 'v' prefix
This approach ensures that version comparisons are done consistently within the same format, aligning with the broader Go ecosystem's practice of supporting the 'v' prefix in semantic versioning (as noted in golang.org/x/mod/semver).

feat: support semver with v prefix when evaluate values

---

ui/dashboard/src/pages/members/member-modal/add-member-modal/environment-roles.tsx

The add environment button can be clicked infinitive on the member's create/update page. It should disable the button when it reaches the max number of environments in the organization.
Fix #1629

fix(ui/dashboard): disabled add environment btn when it reaches the max number of environments

---

ui/dashboard/src/components/info-message/index.tsx
ui/dashboard/src/pages/api-keys/api-key-modal/filter-api-key-modal/index.tsx
ui/dashboard/src/pages/experiments/experiments-modal/filter-experiment-modal/index.tsx
ui/dashboard/src/pages/members/member-modal/filter-member-modal/index.tsx
ui/dashboard/src/pages/notifications/notification-modal/filter-notification-modal/index.tsx
ui/dashboard/src/pages/organizations/organization-modal/filter-organization-modal/index.tsx
ui/dashboard/src/pages/projects/project-modal/filter-project-modal/index.tsx
ui/dashboard/src/pages/pushes/push-modal/filter-push-modal/index.tsx
ui/dashboard/src/pages/user-segments/user-segment-modal/filter-segment-modal/index.tsx

The button should only be enabled after the user selects the filter value.
Check all the other list pages.
Fix #1645

fix(ui/dashboard): submit button is not being validated on the filter on the project list page

---

ui/dashboard/public/locales/en/form.json
ui/dashboard/public/locales/ja/form.json
ui/dashboard/src/pages/members/member-modal/add-member-modal/index.tsx
ui/dashboard/src/pages/members/member-modal/edit-member-modal/index.tsx

Change it from "Select tags" to "Tags can be used to group members as teams".
Fix #1630

chore(ui/dashboard): change tags place holder on the member page

---

pkg/feature/storage/v2/sql/feature/count_features.sql
pkg/feature/storage/v2/sql/feature/count_features_by_experiment.sql
pkg/feature/storage/v2/sql/feature/select_feature_count_by_status.sql
pkg/feature/storage/v2/sql/feature/select_features.sql
pkg/feature/storage/v2/sql/feature/select_features_by_experiment.sql

List features return duplicated data because pair of feature id and environment can exist in different version in feature_last_used_info table

fix: duplicate features returned in the list api

---

ui/dashboard/src/auth/auth-context.tsx
ui/dashboard/src/auth/utils.ts
ui/dashboard/src/components/navigation/my-projects.tsx
ui/dashboard/src/hooks/use-toast.tsx

When accessing the console after a while, it always selects the first environment from the list.
The local storage should have the last selected environment ID after the user logs in. If the selected environment ID is not present in the list, it should force the user to re-login.
Fix #1647

fix(ui/dashboard): admin console always selects the first environment in the list

---

pkg/feature/storage/v2/sql/feature/count_features_by_experiment.sql
pkg/feature/storage/v2/sql/feature/select_features_by_experiment.sql

- Left join can return features without experiment, switch to join
- Remove feature version join condition, should find in any version
Fix https://github.com/bucketeer-io/bucketeer/issues/1670

chore: correctly filter feature with experiment

---

pkg/api/api/grpc_validation.go
pkg/api/api/grpc_validation_test.go
pkg/subscriber/processor/evaluation_events_dwh.go

- Add validation for empty variation_id when the reason is about error.
- Set  variation_id 'default' when the reason is default, variation_id is empty in dwh subscriber. 
- Add tests.

fix: add validation for empty variation_id and set 'default'

---

pkg/batch/api/api_test.go
pkg/experiment/storage/v2/experiment.go
pkg/experiment/storage/v2/experiment_test.go
pkg/experiment/storage/v2/goal.go
pkg/experiment/storage/v2/goal_test.go
pkg/storage/v2/mysql/client.go
pkg/storage/v2/mysql/mock/client.go

This pull request refactors the `experimentStorage` and `goalStorage` to use `mysql.QueryExecer` instead of `mysql.Client` and updates the corresponding tests to reflect this change. The main changes involve replacing `client` with `qe` in the storage structs and updating method calls accordingly.
This PR is a refactor to the deprecation of `Client.Qe()` in the PR below.
https://github.com/bucketeer-io/bucketeer/pull/1549
`Client.Qe()` is unnecessary so it has been removed.

refactor: change the Experiment storage scope to QueryExecer

---

Makefile

When the docker doesn't have privilege, docker load must be failed since the permission issue.

fix: docker load image failure when it doesn't have privileges

---

Makefile

To develop on macOS, it's better to pass the platform flag and fix the platform env for Go.

chore: improve docker build when using dev container on macos

---

Makefile

Due to the changes made in this [PR](https://github.com/bucketeer-io/bucketeer/pull/1680), the docker build fails on the `aarch64` Mac.

fix: docker build fails when using apple cpu architecture

---

pkg/notification/sender/notifier/slack.go
pkg/notification/sender/notifier/slack_test.go

fix #1192 
The ID in the URL must be the Flag ID, not the auto operation ID for AutoOpsRule and ProgressiveRollout.

fix: update domain event attachment creation to use feature_id for slack url of AutoOpsRule and ProgressiveRollout

---

pkg/notification/api/admin_subscription.go
pkg/notification/api/admin_subscription_test.go
pkg/notification/api/subscription.go
pkg/notification/api/subscription_test.go
pkg/notification/storage/v2/admin_subscription.go
pkg/notification/storage/v2/admin_subscription_test.go
pkg/notification/storage/v2/mock/admin_subscription.go
pkg/notification/storage/v2/mock/subscription.go
pkg/notification/storage/v2/sql/admin_subscription/select_admin_subscription_v2_any.sql
pkg/notification/storage/v2/sql/admin_subscription/select_admin_subscription_v2_count.sql
pkg/notification/storage/v2/sql/subscription/select_subscription_v2_any.sql
pkg/notification/storage/v2/sql/subscription/select_subscription_v2_count.sql
pkg/notification/storage/v2/subscription.go
pkg/notification/storage/v2/subscription_test.go

This pull request focuses on refactoring the subscription listing methods in the `NotificationService` to simplify the code and enhance maintainability. The changes include replacing the use of `whereParts` and other individual parameters with a unified `ListOptions` struct, which consolidates filters, orders, and other query options.
relate of #1475

refactor: change the list retrieval API in the notification package to use ListOption

---

pkg/push/api/api.go
pkg/push/api/api_test.go
pkg/push/storage/v2/mock/push.go
pkg/push/storage/v2/push.go
pkg/push/storage/v2/push_test.go
pkg/push/storage/v2/sql/push/count_pushes.sql
pkg/push/storage/v2/sql/push/list_pushes.sql
pkg/storage/v2/mysql/query.go
pkg/storage/v2/mysql/query_test.go
pkg/subscriber/processor/push_sender.go

This pull request includes significant changes to the `PushService` and its related components to improve the handling of push listing and filtering. The changes involve the refactoring of methods to use a new `mysql.ListOptions` structure instead of the previous `mysql.WherePart` filters, and the update of test cases accordingly.

refactor: change the list retrieval API in the push package to use ListOption

---

.github/workflows/push-image.yaml

Due to this [PR](https://github.com/bucketeer-io/bucketeer/pull/1667) a major update from v1.27.0 to v2.0.0 broke the current slack workflow.
Error: https://github.com/bucketeer-io/bucketeer/actions/runs/14331919913/job/40169984159

ci: fix unexpected input error when sending slack notifications

---

manifests/bucketeer/charts/api/templates/multi-cluster-ingress.yaml
manifests/bucketeer/charts/api/values.yaml
manifests/bucketeer/charts/web/templates/multi-cluster-ingress.yaml
manifests/bucketeer/charts/web/values.yaml

GCP allows us to attach multiple SSL certificates to the same target proxy. This means you can update the frontend configuration without immediately deprecating the old certificate. By offering both certificates, clients that initiate new connections will negotiate using either certificate, and the new certificate will be used for new connections when appropriate.
By doing this, we can avoid request failure when updating the certificate.
We support this when using single ingress, but we didn't implement it when using multi-cluster ingress.
E.g.
```yaml
tls:
secrets:
- secretName: bucketeer-old-cert
- secretName: bucketeer-new-cert
```

chore: add multiple tls for mci

---

pkg/auditlog/api/api.go

Fix this error in audit log page,
`TypeError: Cannot read properties of undefined (reading 'message')`
In this pr (https://github.com/bucketeer-io/bucketeer/pull/1684),
removing setting of `auditlog.LocalizedMessage` could cause this error.

fix: add localized message to ListAuditLogs

---

pkg/eventcounter/api/api.go
pkg/eventcounter/api/api_test.go

fix #1635 
The local benchmark test showed this change makes the execution 2x faster.

perf: optimize GetEvaluationTimeseriesCount for concurrent processing

---

pkg/subscriber/processor/auditlog_persister.go

The `createAuditLogsMySQL` func is also being used to create admin logs, and it was not acknowledging the audit logs messages correctly.

fix: admin audit logs not being acknowledged

---

pkg/eventcounter/api/api.go
pkg/eventcounter/api/api_test.go

The user count of day unit causes the results to change each time on the evaluation console.
The `newPFMergeKey` function was generating cache keys based only on feature ID and environment ID, without including the variation ID. This caused all goroutines to operate on the same Redis keys, leading to race conditions where one goroutine would delete or modify keys that other goroutines were still using.
We modified the `newPFMergeKey` function to include the variation ID in the generated keys:
```go
func newPFMergeKey(
kind, featureID, environmentId string,
variationID string, // Added variation ID parameter
) string {
return cache.MakeKey(
fmt.Sprintf("%s:%s", pfMergeKind, kind),
fmt.Sprintf("%s:%s:%s", pfMergeKey, featureID, variationID), // Include variation ID in key
environmentId,
)
} …
```

fix: add variationID parameter to newPFMergeKey

---

migration/mysql/20250411093510_update_audit_log_table.sql
migration/mysql/atlas.sum

fix #1623
Currently, `ListAuditLogs` commonly filter by environment_id and sort by timestamp in descending order, which is not optimized by existing indexes. Adding this composite index will reduce query execution time and improve overall application response time.

perf: add indexes to audit_log table for improved query performance

---

pkg/autoops/api/api.go
pkg/autoops/api/api_test.go
pkg/autoops/api/progressive_rollout.go
pkg/autoops/api/stop_progressive_rollout_operation.go
pkg/autoops/storage/v2/auto_ops_rule_test.go
pkg/autoops/storage/v2/progressive_rollout_test.go
pkg/feature/api/feature.go
pkg/notification/api/admin_subscription.go
pkg/notification/api/subscription.go
pkg/notification/storage/v2/admin_subscription_test.go
pkg/notification/storage/v2/subscription_test.go
pkg/opsevent/storage/v2/mock/ops_count.go
pkg/opsevent/storage/v2/ops_count.go
pkg/opsevent/storage/v2/ops_count_test.go
pkg/opsevent/storage/v2/sql/ops_count/insert_ops_count.sql
pkg/opsevent/storage/v2/sql/ops_count/select_ops_counts.sql
pkg/push/api/api.go
pkg/push/storage/v2/push_test.go
pkg/storage/v2/mysql/query.go
pkg/subscriber/processor/push_sender.go

This pull request includes changes to the `opsevent` and related components to support multiple `InFilters` instead of a single `InFilter`. Additionally, it updates the corresponding tests and mock implementations to align with these changes.

refactor: change the list retrieval API in the opsevent package to use ListOption

---

pkg/experiment/api/experiment.go
pkg/experiment/api/experiment_test.go
pkg/experiment/storage/v2/experiment.go
pkg/experiment/storage/v2/experiment_test.go
pkg/experiment/storage/v2/mock/experiment.go
pkg/experiment/storage/v2/sql/experiment/count_experiment.sql
pkg/experiment/storage/v2/sql/experiment/select_experiments.sql

This pull request includes significant refactoring of the `ListExperiments` method in the `experimentService` and related files to improve the handling of query filters and options. The changes primarily involve replacing the old `WherePart` and other individual filter constructs with a new `ListOptions` structure that consolidates all query parameters.

refactor: change the list retrieval API in the experiment package to use ListOption

---

test/e2e/tag/tag_test.go

I want to debug why the test fails here randomly.
The unique key is `UNIQUE KEY `name` (`name`,`environment_id`,`entity_type`)`.
It should be fine, but sometimes it creates a new one.
```sh
tag_test.go:84: Different create time. Expected: 1746009776, Actual: 1746009782
--- FAIL: TestUpsertAndListTag (5.85s)
```

test: change log info in the upsert tag e2e test

---

ui/dashboard/src/pages/feature-flags/collection-layout/elements/utils.ts

I checked the last used info object, and the timestamp is indeed older than 7 days, but on the list page, it shows active.
Fix #1746

fix(ui/dashboard): flag status showing incorrect

---

pkg/tag/api/api.go
pkg/tag/api/api_test.go
pkg/tag/storage/tag_test.go

This pull request refactors the `TagService` to use a `tagStorage` instance instead of creating a new `TagStorage` object in each method. Additionally, it introduces comprehensive unit tests for the `TagService` to improve test coverage and reliability.

test: add unit tests to tag package

---

pkg/auditlog/api/api.go
pkg/auditlog/api/api_test.go
pkg/auditlog/storage/v2/admin_audit_log.go
pkg/auditlog/storage/v2/admin_audit_log_test.go
pkg/auditlog/storage/v2/audit_log.go
pkg/auditlog/storage/v2/audit_log_test.go
pkg/auditlog/storage/v2/mock/admin_audit_log.go
pkg/auditlog/storage/v2/mock/audit_log.go
pkg/auditlog/storage/v2/sql/adminauditlog/select_admin_audit_log_v2.sql
pkg/auditlog/storage/v2/sql/adminauditlog/select_admin_audit_log_v2_count.sql
pkg/auditlog/storage/v2/sql/auditlog/select_audit_log_v2_count.sql
pkg/auditlog/storage/v2/sql/auditlog/select_audit_logs_v2.sql

This pull request refactors the audit log services and storage layers to use a new `mysql.ListOptions` struct for query filtering, ordering, and pagination. It replaces the older `mysql.WherePart` and individual parameters with a more flexible and centralized approach. Additionally, corresponding test cases and imports have been updated to align with these changes.

refactor: change the list retrieval API in the auditlog package to use ListOption

---

pkg/feature/domain/feature.go
pkg/feature/domain/feature_test.go
pkg/feature/domain/feature_update.go

- Refactored the code to apply variation changes as the first step when the action is CREATE or UPDATE
- Refactored the code to apply variation changes as the last step when the action is DELETE
- Changed to use the variation ID (UUID) from the admin console instead of generating on the backend and added a UUID validation
--- 
This pull request introduces a significant refactor to the `Feature` update process, focusing on improving the handling of variation changes. It also includes enhancements to test coverage and debugging outputs. The most notable changes involve splitting variation changes into separate steps for better data integrity, adding UUID validation, and improving test cases for variations.
* Introduced a two-step approach to handling variation changes in the `Update` …

fix: cannot update flag when creating a new variation and set the same variation to a rule or off variation

---

pkg/feature/api/flag_trigger.go
pkg/feature/api/flag_trigger_test.go
pkg/feature/storage/v2/flag_trigger.go
pkg/feature/storage/v2/flag_trigger_test.go
pkg/feature/storage/v2/mock/flag_trigger.go
pkg/feature/storage/v2/sql/flag_trigger/count_flag_trigger.sql
pkg/feature/storage/v2/sql/flag_trigger/list_flag_trigger.sql

This pull request refactors the `ListFlagTriggers` functionality in the `FeatureService` and its associated storage layer to use a new `mysql.ListOptions` struct for query construction. This change simplifies and standardizes the query logic, improves maintainability, and updates corresponding tests and mock implementations.

refactor: change the list retrieval API in the flagTrigger package to use ListOption 

---

pkg/feature/api/segment.go
pkg/feature/api/segment_test.go
pkg/feature/storage/v2/mock/segment.go
pkg/feature/storage/v2/segment.go
pkg/feature/storage/v2/segment_test.go
pkg/feature/storage/v2/sql/segment/delete_segment.sql
pkg/feature/storage/v2/sql/segment/get_segment.sql
pkg/feature/storage/v2/sql/segment/insert_segment.sql
pkg/feature/storage/v2/sql/segment/update_segment.sql

This pull request refactors the `ListSegments` functionality and improves the segment storage layer by introducing reusable SQL query files, updating the method signatures, and adding comprehensive unit tests. These changes enhance code maintainability, modularity, and test coverage.

refactor: change Segment related list retrieval APIs to use ListOption

---

pkg/account/api/api_key.go
pkg/account/api/api_key_test.go
pkg/account/storage/v2/api_key.go
pkg/account/storage/v2/api_key_test.go
pkg/account/storage/v2/mock/storage.go
pkg/account/storage/v2/sql/api_key_v2/select_api_key_v2.sql
pkg/account/storage/v2/sql/api_key_v2/select_api_key_v2_count.sql
pkg/account/storage/v2/storage.go

This pull request refactors the `ListAPIKeys` functionality in the `pkg/account` package to improve code maintainability and simplify query construction. The changes replace the use of multiple parameters for query filters and options with a single `mysql.ListOptions` struct, affecting both the main implementation and associated test cases.

refactor: change apikey related list retrieval APIs to use ListOption

---

pkg/account/storage/v2/account.go
pkg/account/storage/v2/api_key.go
pkg/auditlog/storage/v2/admin_audit_log.go
pkg/auditlog/storage/v2/audit_log.go
pkg/autoops/storage/v2/progressive_rollout.go
pkg/environment/storage/v2/environment.go
pkg/environment/storage/v2/organization.go
pkg/environment/storage/v2/project.go
pkg/experiment/storage/v2/experiment.go
pkg/feature/storage/v2/flag_trigger.go
pkg/notification/storage/v2/admin_subscription.go
pkg/notification/storage/v2/subscription.go
pkg/push/storage/v2/push.go
pkg/storage/v2/mysql/query.go
pkg/storage/v2/mysql/query_test.go

This pull request addressed the following issue.
- Due to refactoring of ListOption, there was an issue with the query to get the total number, which caused the total number to be retrieved incorrectly.
- There was an issue where paging on the Auditlog list screen, etc. could not be displayed properly.
This pull request refactors multiple `List` methods across various storage modules to improve query construction for counting total records. The changes replace the use of `mysql.ConstructQueryAndWhereArgs` with a more flexible approach that directly appends `WHERE` clauses to the base SQL query when filtering options are provided. If no options are specified, the base query is executed without modification.

fix: mysql no rows error when using pagination

---

pkg/feature/api/tag.go
pkg/feature/api/tag_test.go
pkg/tag/api/api.go
pkg/tag/api/api_test.go
pkg/tag/storage/mock/tag.go
pkg/tag/storage/sql/count_tags.sql
pkg/tag/storage/sql/select_tags.sql
pkg/tag/storage/tag.go
pkg/tag/storage/tag_test.go

This pull request refactors the `ListTags` functionality across multiple components to adopt a new `mysql.ListOptions` structure, improving maintainability and consistency. The changes include updates to the `ListTags` method, its associated tests, and the SQL query construction logic.

refactor: change ListTags to utilize ListOptions

---

pkg/rpc/gateway/gateway.go
pkg/rpc/gateway/gateway_test.go
test/e2e/gateway/api_test.go
test/e2e/util/rest.go

Fix https://github.com/bucketeer-io/bucketeer/issues/1803
Related to https://github.com/bucketeer-io/android-client-sdk/pull/230
Add a temporary custom JSON unmarshaler to handle boolean fields sent as strings from the Android SDK. This addresses a compatibility issue that arose after switching from Envoy JSON transcoder to gRPC-Gateway.
Changes:
- Implement customJSONPb struct with custom Unmarshal method
- Support multiple boolean string representations ("true", "false", "1", "0", etc.)
- Handle nested JSON structures with recursive boolean string conversion
- Preserve original errors for invalid inputs
- Add comprehensive test coverage for all scenarios
The unmarshaler follows this logic:
1. First attempts at standard protobuf unmarshaling
2. If that fails, checks for boolean string …

chore: add custom JSON unmarshaler for boolean string compatibility

---

ui/dashboard/src/components/navigation/index.tsx

When the user is in the organization settings menu, clicking on the Bucketeer logo redirects to the flag list page, but it doesn't update the sidebar.
Fix #1871

fix(ui/dashboard): sidebar not updating when clicking on the bucketeer logo

---

ui/dashboard/src/@api/notification/notifications-fetcher.ts
ui/dashboard/src/@api/push/pushes-fetcher.ts
ui/dashboard/src/auth/utils.ts
ui/dashboard/src/pages/notifications/collection-loader/index.tsx
ui/dashboard/src/pages/notifications/collection-loader/use-fetch-notifications.ts
ui/dashboard/src/pages/notifications/notification-modal/add-notification-modal/index.tsx
ui/dashboard/src/pages/notifications/notification-modal/edit-notification-modal/index.tsx
ui/dashboard/src/pages/pushes/collection-layout/data-collection.tsx
ui/dashboard/src/pages/pushes/collection-loader/index.tsx
ui/dashboard/src/pages/pushes/collection-loader/use-fetch-pushes.ts
ui/dashboard/src/pages/pushes/push-modal/add-push-modal/index.tsx
ui/dashboard/src/pages/pushes/push-modal/edit-push-modal/index.tsx

For the FCM and Slack Create pages, I need to change the implementation of the environment list.
We must check the environment_roles from the local storage (retrieved by the get_me API), and create a list of environments where the user has the Editor role instead of calling the list_environments API, which includes all environments even if the user doesn't belong to them.
Currently, if the user tries to create using an environment he doesn't belong to, the request will fail.
Fix #1870

feat(ui/dashboard): restrict the environment list when creating fcm and slack notifications

---

ui/dashboard/src/@api/features/features-fetch.ts
ui/dashboard/src/pages/feature-flags/collection-layout/grid-view-collection.tsx
ui/dashboard/src/pages/feature-flags/collection-loader/index.tsx
ui/dashboard/src/pages/feature-flags/collection-loader/use-fetch-flags.ts
ui/dashboard/src/pages/feature-flags/flags-modal/filter-flag-modal/index.tsx
ui/dashboard/src/pages/feature-flags/overview/index.tsx
ui/dashboard/src/pages/feature-flags/page-content.tsx
ui/dashboard/src/pages/feature-flags/types.ts

Add the new filters to the flag list page.
- Status (Active, Inactive, and New)
- Has a flag as a rule (Yes or No)
For the Status, I want you to also add template filters on the cards at the top of the page.
Fix #1869

feat(ui/dashboard): add status and has a flag as a rule filter options

---

pkg/account/domain/account.go
pkg/account/domain/account_test.go
ui/dashboard/src/@locales/ja/common.json
ui/dashboard/src/@locales/ja/form.json

Fix https://github.com/bucketeer-io/bucketeer/issues/1943
Due to schema changes for the new console, the old members in the account table don't have the first and last names, which are being validated in the new API for the new console.
So, I changed the validation to allow the update if the `name` field is not empty.

fix: cannot update an existing member on the new console

---

pkg/experiment/storage/v2/sql/goal/select_goal.sql
pkg/experiment/storage/v2/sql/goal/select_goals.sql

Use JSON_CONTAINS in stead of LIKE in where condition to correctly filter in used goals
to fix https://github.com/bucketeer-io/bucketeer/issues/1947

fix: incorrect goal's in used status

---

test/e2e/gateway/api_test.go
test/e2e/util/rest.go

Error log:
```sh
=== CONT  TestHTTPBooleanStringHandling/boolean_string_false_uppercase
api_test.go:371: Failed to unmarshal response: json: cannot unmarshal string into Go struct field Reason.evaluations.evaluations.reason.type of type feature.Reason_Type, data: {"state":"FULL", "evaluations":{"id":"13298090430196981890", "evaluations":[{"id":"e2e-test-16188104694-feature-id-c710f04f-764e-4147-9a74-988983c830e8:1:test-user-id", "featureId":"e2e-test-16188104694-feature-id-c710f04f-764e-4147-9a74-988983c830e8", "featureVersion":1, "userId":"test-user-id", "variationId":"31fb70c7-d15b-4ae0-896d-e9e486d1d5e1", "variation":{"id":"31fb70c7-d15b-4ae0-896d-e9e486d1d5e1", "value":"B", "name":"Variation B", "description":""}, "reason":{"type":"OFF_VARIATION", "ruleId":""}, "variationValue":"B", …
```

test: fix flaky e2e boolean string handling test

---

pkg/subscriber/cmd/server/server.go
pkg/subscriber/processor/evaluation_events_dwh.go
pkg/subscriber/processor/events_dwh_persister.go
pkg/subscriber/processor/goal_events_dwh.go

We can't collect BigQuery metrics now, so added metrics registerer to event writers and persisters.

chore: add metrics registerer to event writers and persisters

---

pkg/storage/v2/bigquery/querier/metrics.go
pkg/storage/v2/bigquery/writer/metrics.go
pkg/storage/v2/bigquery/writer/metrics_test.go
pkg/subscriber/cmd/server/server.go

Fix the panic error.
The subscriber creates multiple queriers and writers for evaluation and goal events in the same processor, which causes it to panic. So, I implemented the `RegisterOnce`, which we already use in some places similar to this.
```sh
panic: duplicate metrics collector registration attempted
goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(...)
/home/runner/work/bucketeer/bucketeer/vendor/github.com/prometheus/client_golang/prometheus/registry.go:406
github.com/bucketeer-io/bucketeer/pkg/storage/v2/bigquery/writer.RegisterMetrics(...)
/home/runner/work/bucketeer/bucketeer/pkg/storage/v2/bigquery/writer/metrics.go:107
github.com/bucketeer-io/bucketeer/pkg/storage/v2/bigquery/writer.NewWriter({0x1dc5950, 0xc000c84af0}, …
```

fix: duplicate metrics collector registration attempted

---

pkg/feature/api/feature.go
pkg/feature/domain/feature_test.go
pkg/feature/domain/feature_update.go
pkg/feature/domain/feature_update_test.go

When the console sends in the flag update API, the `enabled` and `archived` fields, the new update logic still uses old functions from the old UI, which updates the `updated_at` when setting those fields. So, even if the boolean value is the same, because the `updated_at` was updated, MySQL saves with no issues, causing an incorrect state in the audit logs with only the `updated_at`.
If the console tries to send those two fields without changing the current state, it will return the following error, so we can know there is something wrong next time.
```sh
{"code":2, "message":"feature: unexpected affected rows", "details":[]}
```
- Shallow Copy Bug: `copier.Copy` caused modifications to the updated feature to also modify the original feature, making copier.Copy always sees them as …

fix: flag only updating the updated_at field

---

pkg/subscriber/processor/auditlog_persister.go

I'm investigating the following error when saving the audit log.
```sh
ERROR 2025-07-15T02:18:13.876800485Z [resource.labels.containerName: subscriber] Failed to put audit logs
"error": "Error 1406 (22001): Data too long for column 'entity_data' at row 1"
```
The cause was that the user saved a very large list of user IDs in the individual targeting. So, when saving the entire feature object in the entity_data column exceeded the max limit of 64 KB.
I have asked the maintainer to use the user segment instead, and I have purged the message from PubSub since we are not going to support an entity larger than 64 KB at the moment.

chore: improve error log when saving audit logs

---

pkg/environment/api/organization.go

When accessing the Organization settings with a non-system admin account, it showed permission denied error logs.
Since the `checkOrganizationRole` already checks for the system admin, I have removed the `checkSystemAdminRole` check to prevent false logs.

fix: showing false permission denied error

---

pkg/account/api/account.go
pkg/account/api/account_test.go
pkg/account/api/admin_account.go
pkg/account/api/api_key.go
pkg/account/domain/account.go
pkg/notification/api/subscription.go
pkg/push/api/api.go
pkg/tag/api/api.go

Fix https://github.com/bucketeer-io/bucketeer/issues/2023 https://github.com/bucketeer-io/bucketeer/issues/2024 https://github.com/bucketeer-io/bucketeer/issues/2025
- Fixed the issue not listing all accounts when the current user is the owner
- Fixed list environments, API keys, subscriptions, and Slack notifications not showing to an owner user
- Fixed unexpected affected rows when creating accounts

fix: admin access only entities are not listing for owner users

---

manifests/bucketeer/charts/batch/values.dev.yaml
manifests/bucketeer/charts/subscriber/values.yaml
manifests/bucketeer/values.dev.yaml
pkg/cache/v3/mock/user.go
pkg/cache/v3/user.go
pkg/cache/v3/user_test.go
pkg/subscriber/processor/evaluation_events_evaluation_count_event_persister.go

This pull request introduces a new feature to support configurable TTL (Time-To-Live) for user attributes in the caching layer and updates related configurations and tests. The main changes include adding a `UserAttributeTTLDay` parameter, modifying the caching logic to use this parameter, and updating tests to validate the new functionality.
This PR allows you to change the storage period of `UserAttributeKeys` depending on the environment, improving the performance of e2e tests.

chore: change the ttl of UserAttributeKeys to config management

---

pkg/feature/api/error.go
pkg/feature/api/feature.go
pkg/feature/api/validation.go
pkg/feature/api/validation_test.go
pkg/feature/domain/feature.go
pkg/feature/domain/feature_test.go
pkg/feature/domain/feature_update.go
pkg/feature/domain/feature_update_test.go
pkg/feature/domain/migration.go
pkg/feature/domain/migration_test.go
ui/dashboard/src/pages/feature-flag-details/targeting/default-rule/index.tsx
ui/dashboard/src/pages/feature-flag-details/targeting/utils.ts

Fix https://github.com/bucketeer-io/bucketeer/issues/2037
There was a bug when adding and removing variations. When adding, it wasn't adding the new variation to the Rules and Default Strategy, and when removing, it wasn't deleting from the targets, rules, and default strategy, causing a different state in the DB.
I have implemented a temporary migration in the API so the user can use the console as soon as possible. However, we will probably need a DB-level migration, and it will take some time to do it carefully.
Also, I found another issue when deleting a variation used in another Flag as a prerequisite or a rule. After deleting, the prerequisite and rule show empty for the variation ID value. This will also need a migration.
- Fixed variation not being added to Rules and Default …

fix: variation deletion not deleting references in targets, rules, and default strategy

---

pkg/autoops/api/api.go
pkg/autoops/api/flag_trigger_operation.go
pkg/autoops/api/flag_trigger_operation_test.go

Fix: https://github.com/bucketeer-io/bucketeer/issues/2051
When the auto operation is triggered, the flag version is not incremented, which will not update the SDK client cache because the user evaluation ID is based on the feature_id, feature_version, and user_id.
- Fixed flag version not being incremented when the auto operation updates a flag
- Fixed audit log not being created when the flag is updated by an auto operation

fix: auto operation not incrementing flag version

---

docker-compose/compose.yml
docker-compose/env.default
manifests/bucketeer/charts/api/templates/deployment.yaml
manifests/bucketeer/charts/api/values.yaml
manifests/bucketeer/charts/batch/templates/deployment.yaml
manifests/bucketeer/charts/batch/values.yaml
manifests/bucketeer/charts/subscriber/templates/deployment.yaml
manifests/bucketeer/charts/subscriber/values.yaml
manifests/bucketeer/charts/web/templates/deployment.yaml
manifests/bucketeer/charts/web/values.yaml
manifests/bucketeer/values.dev.yaml
pkg/cli/app.go

fix #2105
This PR implements pprof (Go profiler) debug endpoints for the Bucketeer application. This enables performance analysis and bottleneck identification in production and testing environments.
1. **New Command Line Flags**:
- `--enable-pprof`: Enable pprof endpoints (default: `false`)
- `--pprof-address`: Port number for pprof server (default: `127.0.0.1:6060`)
2. **Pprof Server Implementation**:
```go
if *enablePprof {
go func() {
if err := http.ListenAndServe(*pprofAddr, nil); err != nil {
logger.Error("Failed to start pprof server", zap.Error(err))
}
}()
}
```
```bash
./bin/api --enable-pprof=true --pprof-address=127.0.0.1:6060 [other-flags]
./bin/batch --enable-pprof=true --pprof-address=127.0.0.1:6060 [other-flags]
./bin/subscriber --enable-pprof=true …
```

feat: add pprof debug option

---

.github/.devcontainer/Dockerfile

This PR removes the `unminimize` step and inlines the minimal set of packages needed for `man` into the existing **Install packages in optimized order for better layer caching** block. Functionality is unchanged (man pages are available), but the image now builds reliably in non-interactive environments.
Our current devcontainer build fails in BuildKit/CI because `unminimize` expects an interactive TTY and exits with a non-zero code. From the Docker Build summary:
```
process "/bin/sh -c apt-get update && export DEBIAN_FRONTEND=noninteractive \
&& yes | unminimize 2>&1" did not complete successfully: exit code: 123
```
Replacing `unminimize` eliminates this non-interactive failure mode while keeping the intended outcome (having `man` available).

deps: remove unminimize and add minimal man deps for dev container

---

pkg/error/error.go
pkg/notification/api/admin_subscription.go
pkg/notification/api/api.go
pkg/notification/api/error.go
pkg/notification/api/subscription.go
pkg/notification/command/command.go
pkg/notification/domain/subscription.go
pkg/notification/storage/v2/admin_subscription.go
pkg/notification/storage/v2/subscription.go

This pull request refactors error handling in the `notification` package to standardize and simplify the way gRPC errors are constructed and returned. Instead of manually building detailed error responses with localized messages, the code now uses a centralized utility (`api.NewGRPCStatus`) and new error constructors from the shared `error` package. This change improves consistency, maintainability, and clarity of error handling across notification service APIs.
I have also standardized the process of assigning ErrorInfo to GRPCStatus for each error via api.NewGRPCStatus.
This ErrorInfo will be used when moving i18n to the frontend(https://github.com/bucketeer-io/bucketeer/issues/1253), and we plan to generate error messages etc. based on this information on the frontend.

refactor: notificationAPI related error handling in Notification package

---

pkg/api/api/grpc_status.go
pkg/environment/api/api.go
pkg/environment/api/environment_v2.go
pkg/environment/api/environment_v2_test.go
pkg/environment/api/error.go
pkg/environment/api/organization.go
pkg/environment/api/organization_test.go
pkg/environment/api/project.go
pkg/environment/api/project_test.go
pkg/environment/command/command.go
pkg/environment/domain/organization.go
pkg/environment/storage/v2/environment.go
pkg/environment/storage/v2/organization.go
pkg/environment/storage/v2/project.go
pkg/error/error.go
pkg/eventcounter/api/api.go
pkg/eventcounter/api/api_test.go
pkg/eventcounter/api/error.go
pkg/eventcounter/storage/v2/event.go
pkg/eventcounter/storage/v2/experiment_result.go

This pull request refactors error handling in the environment API and its tests to standardize the conversion of internal errors to gRPC status responses. It also adds support for the `FAILED_PRECONDITION` error type in gRPC status conversion. The changes improve maintainability and consistency of error reporting throughout the service.

refactor: change error definition in EventCounter PKG and Environment PKG to Bucketeer error

---

pkg/feature/domain/feature.go

Add `printf` temporary debug log because it's difficult to add logger.

chore: add temporary logging for missing feature dependencies
